-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.5.1.0.xml
-- Ran at: 04.08.14 15:23
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-01::akn::(Checksum: 6:b4b1438959cdfa538f2ecc0d852116c8)
ALTER TABLE ORC_PROCESS_FIFO_SCHEDULE ALTER COLUMN PFS_ID SET DATA TYPE VARCHAR(50);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_FIFO_SCHEDULE');

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-02::akn::(Checksum: 6:6f0693225b07d78edc17111d23bfa338)
ALTER TABLE ORC_ALERT_DATA ADD NODE_ID VARCHAR(255) DEFAULT 'ORC' NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_ALERT_DATA');

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-03::akn::(Checksum: 6:91ed9b5d75595fe139cfc5761652db1d)
DROP INDEX IDX_SEQ_COUNTER_CATEGORY;

UPDATE ORC_SEQUENCE_COUNTER SET SCO_CATEGORY = 'ORC' WHERE SCO_CATEGORY IS NULL;

ALTER TABLE ORC_SEQUENCE_COUNTER ALTER COLUMN  SCO_CATEGORY SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEQUENCE_COUNTER');

ALTER TABLE ORC_SEQUENCE_COUNTER ADD CONSTRAINT PK_SEQ_COUNTER_CAT PRIMARY KEY (SCO_CATEGORY);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEQUENCE_COUNTER');

DROP INDEX IDX_MSG_DATA_MSG_ID;

UPDATE ORC_MESSAGE_DATA SET MSD_MSG_ID = 'ORC' WHERE MSD_MSG_ID IS NULL;

ALTER TABLE ORC_MESSAGE_DATA ALTER COLUMN  MSD_MSG_ID SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_DATA');

ALTER TABLE ORC_MESSAGE_DATA ADD CONSTRAINT PK_MSG_DATA_MSG_ID PRIMARY KEY (MSD_MSG_ID);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_DATA');

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-04::akn::(Checksum: 6:706e1b31fb477bed8328e25a8d68791d)
CREATE TABLE ORC_COMMIT_DESC (OCD_TAID VARCHAR(255) NOT NULL, OCD_TIME TIMESTAMP, OCD_NODE VARCHAR(255) NOT NULL);

ALTER TABLE ORC_COMMIT_DESC ADD CONSTRAINT PK_COMDE_TAID_NODE PRIMARY KEY (OCD_TAID, OCD_NODE);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_COMMIT_DESC');

ALTER TABLE ORC_WORK_QUEUE ADD NEXT_SCHEDULE_TIME TIMESTAMP;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_WORK_QUEUE');

CREATE INDEX IDX_WORK_QUEUE_S_T_Q_N ON ORC_WORK_QUEUE(STATE, TARGET_NODE, QUEUE_TYPE, NEXT_SCHEDULE_TIME);

ALTER TABLE ORC_TOPIC_QUEUE ADD NEXT_SCHEDULE_TIME TIMESTAMP;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_TOPIC_QUEUE');

CREATE INDEX IDX_TOPIC_QUEUE_S_T_Q_N ON ORC_TOPIC_QUEUE(STATE, TARGET_NODE, QUEUE_TYPE, NEXT_SCHEDULE_TIME);

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-05::akn::(Checksum: 6:0e0da09b73ddd7c352e513b8e701cc16)
ALTER TABLE ORC_ALERT_DATA ALTER COLUMN DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_ALERT_DATA');

ALTER TABLE ORC_ARCHIVE ALTER COLUMN ARC_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_ARCHIVE');

ALTER TABLE ORC_CHANNEL ALTER COLUMN CHA_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_CHANNEL');

ALTER TABLE ORC_CONTENT_MAPPING ALTER COLUMN CMA_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_CONTENT_MAPPING');

ALTER TABLE ORC_CONTENT_TYPE ALTER COLUMN CTY_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_CONTENT_TYPE');

ALTER TABLE ORC_DBS_PAGE ALTER COLUMN DEL_DATA SET DATA TYPE BLOB(4M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_DBS_PAGE');

ALTER TABLE ORC_EXT_ARCHIVE ALTER COLUMN EXA_REQ_CONTENT SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_EXT_ARCHIVE');

ALTER TABLE ORC_EXT_ARCHIVE ALTER COLUMN EXA_RESP_CONTENT SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_EXT_ARCHIVE');

ALTER TABLE ORC_EXT_ARCHIVE_ERROR ALTER COLUMN ERC_STACK SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_EXT_ARCHIVE_ERROR');

ALTER TABLE ORC_GLOBAL_TRANSACTION ALTER COLUMN OTG_COMMAND SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_GLOBAL_TRANSACTION');

ALTER TABLE ORC_JAVA_CLASS ALTER COLUMN JCL_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_JAVA_CLASS');

ALTER TABLE ORC_LANDSCAPE ALTER COLUMN LAN_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_LANDSCAPE');

ALTER TABLE ORC_LOOKUPTABLE ALTER COLUMN LUT_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_LOOKUPTABLE');

ALTER TABLE ORC_MESSAGE_DATA ALTER COLUMN MSG_MSG_DATA SET DATA TYPE BLOB(1024M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_DATA');

ALTER TABLE ORC_MESSAGE_INTERFACE ALTER COLUMN MIN_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_INTERFACE');

ALTER TABLE ORC_MESSAGE_MAPPING ALTER COLUMN MMA_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_MAPPING');

ALTER TABLE ORC_MESSAGE_TYPE ALTER COLUMN MTY_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_TYPE');

ALTER TABLE ORC_PROCESS_FIFO_SCHED_CACHE ALTER COLUMN PFC_VARIABLES SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_FIFO_SCHED_CACHE');

ALTER TABLE ORC_PROCESS_FIFO_SCHEDULE ALTER COLUMN PFS_VARIABLES SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_FIFO_SCHEDULE');

ALTER TABLE ORC_PROCESS_MODELLS ALTER COLUMN PMO_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_MODELLS');

ALTER TABLE ORC_PROCESS_MODELLS_HIST ALTER COLUMN PMO_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_MODELLS_HIST');

ALTER TABLE ORC_PROCESS_RUNTIME_STATE ALTER COLUMN PRS_VARIABLES SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_RUNTIME_STATE');

ALTER TABLE ORC_PROCESS_SCENARIO ALTER COLUMN PSC_SCENARIO_IMAGE SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_SCENARIO');

ALTER TABLE ORC_PROCESS_SCENARIO_HISTORY ALTER COLUMN PSC_SCENARIO_IMAGE SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_SCENARIO_HISTORY');

ALTER TABLE ORC_PROCESS_WAIT_LIST ALTER COLUMN TOKEN_REFERENCE SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_WAIT_LIST');

ALTER TABLE ORC_PROCESSINSTANCE_STATE ALTER COLUMN PRS_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESSINSTANCE_STATE');

ALTER TABLE ORC_PRS_DESCRIPTION ALTER COLUMN PRS_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PRS_DESCRIPTION');

ALTER TABLE ORC_PRT_PARTNERCONFIG ALTER COLUMN PRT_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PRT_PARTNERCONFIG');

ALTER TABLE ORC_RECOVERY_DATA ALTER COLUMN RDA_LOCAL_VARS SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_RECOVERY_DATA');

ALTER TABLE ORC_SCENARIO_DOC ALTER COLUMN SDO_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SCENARIO_DOC');

ALTER TABLE ORC_SEC_KEYSTORE_V2 ALTER COLUMN OTS_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEC_KEYSTORE_V2');

ALTER TABLE ORC_SEC_TRUSTSTORE_V2 ALTER COLUMN OTS_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEC_TRUSTSTORE_V2');

ALTER TABLE ORC_SEC_USER_CERTIFICATE ALTER COLUMN OUP_CERTIFICATE SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEC_USER_CERTIFICATE');

ALTER TABLE ORC_SEC_USER_PKCS12 ALTER COLUMN OUS_PKCS12STORE SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEC_USER_PKCS12');

ALTER TABLE ORC_SEC_USER_SSH ALTER COLUMN OUS_CERTIFICATE SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEC_USER_SSH');

ALTER TABLE ORC_SVC_DECLARATION ALTER COLUMN SDC_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SVC_DECLARATION');

ALTER TABLE ORC_SVC_PROVIDER ALTER COLUMN SPR_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SVC_PROVIDER');

ALTER TABLE ORC_TIMING_DATA ALTER COLUMN OTD_TIMING SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_TIMING_DATA');

ALTER TABLE ORC_TOPIC_QUEUE ALTER COLUMN WORKOBJECT SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_TOPIC_QUEUE');

ALTER TABLE ORC_TRANSACTION_BRANCH ALTER COLUMN TBR_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_TRANSACTION_BRANCH');

ALTER TABLE ORC_WORK_QUEUE ALTER COLUMN WORKOBJECT SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_WORK_QUEUE');

ALTER TABLE ORC_XML_SCHEMA ALTER COLUMN XSC_DATA SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_XML_SCHEMA');

ALTER TABLE qrtz_blob_triggers ALTER COLUMN blob_data SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE qrtz_blob_triggers');

ALTER TABLE qrtz_calendars ALTER COLUMN calendar SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE qrtz_calendars');

ALTER TABLE qrtz_job_details ALTER COLUMN job_data SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE qrtz_job_details');

ALTER TABLE qrtz_triggers ALTER COLUMN job_data SET DATA TYPE BLOB(10M);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE qrtz_triggers');

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.4.3.2-02::akn::(Checksum: 6:b6e17c03c4c01449cba2d23705e03d6a)
ALTER TABLE ORC_KPI_INSTANCE ADD CONSTRAINT PK_ORC_KPI_INST PRIMARY KEY (KIN_IDENTIFIER);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_KPI_INSTANCE');

ALTER TABLE ORC_KPI_DIM_VALUE ADD CONSTRAINT PK_ORC_KPI_DIM_VAL PRIMARY KEY (KDV_INSTANCEID, KDV_NAME);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_KPI_DIM_VALUE');

ALTER TABLE ORC_KPI_VALUE ADD CONSTRAINT PK_ORC_KPI_VALUE PRIMARY KEY (KVA_INSTANCEID, KVA_TIMEINDEX);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_KPI_VALUE');

