-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.7.0.0.xml
-- Ran at: 7/5/17 12:31 PM
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-1::akn::(Checksum: 6:0b3d233300c07781ba3aa99d28bc503f)
ALTER TABLE ORC_EVENT_PROCESS_TOKEN ALTER COLUMN EVT_ORCHESTRA_LINK SET DATA TYPE VARCHAR(300);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_EVENT_PROCESS_TOKEN');

ALTER TABLE ORC_WORKLIST_TYPE ADD WLT_LABEL VARCHAR(20);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_WORKLIST_TYPE');

ALTER TABLE ORC_EVENT_PROCESS_TOKEN ADD EVT_VARLOG BLOB;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_EVENT_PROCESS_TOKEN');

ALTER TABLE ORC_EVENT_PROCESS_TOKEN ADD EVT_USE_VARLOG INTEGER;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_EVENT_PROCESS_TOKEN');

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-2_Syslog::akn::(Checksum: 6:4d3a527fff1a9cff37c7415b0532f8da)
CREATE TABLE ORC_SYSLOG_QUEUE (ITEMTYPE VARCHAR(256) NOT NULL, DISCRIMINATOR VARCHAR(256) NOT NULL, CREATEDAT TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL, WORKOBJECT BLOB, ID VARCHAR(50) NOT NULL, ACTION CHAR(1) DEFAULT 'W', NAME VARCHAR(256), STATE INTEGER, TARGET_NODE VARCHAR(255), NODE_TICK VARCHAR(255), QUEUE_TYPE VARCHAR(1), PRIORITY INTEGER, ORC_TOPIC_OWNER VARCHAR(256), ORC_TOPIC_ID VARCHAR(256), NEXT_SCHEDULE_TIME TIMESTAMP, DELETETOKEN INTEGER);

ALTER TABLE ORC_SYSLOG_QUEUE ADD CONSTRAINT PK_SYSLOG_ID PRIMARY KEY (ID);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SYSLOG_QUEUE');

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_TOPIC_ID ON ORC_SYSLOG_QUEUE(ORC_TOPIC_ID, QUEUE_TYPE, STATE);

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_TOPIC_OWNER ON ORC_SYSLOG_QUEUE(ORC_TOPIC_OWNER, QUEUE_TYPE, STATE);

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_STATE_TYPE_ID ON ORC_SYSLOG_QUEUE(STATE, QUEUE_TYPE, ID);

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_S_T_Q_N ON ORC_SYSLOG_QUEUE(STATE, ORC_TOPIC_ID, TARGET_NODE, QUEUE_TYPE, NEXT_SCHEDULE_TIME);

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_STAT_TYP_PRIO ON ORC_SYSLOG_QUEUE(STATE, QUEUE_TYPE, PRIORITY, ID);

CREATE TABLE ORC_SYSLOG_QUEUE_DEL_TOPIC (DTO_TOPIC VARCHAR(256) NOT NULL, DTO_DELETETOKEN INTEGER NOT NULL, DTO_GLOBAL INTEGER NOT NULL, DTO_NODEID VARCHAR(32) NOT NULL, DTO_IDENT INTEGER NOT NULL, DTO_QUEUE_TYPE VARCHAR(1) NOT NULL);

ALTER TABLE ORC_SYSLOG_QUEUE_DEL_TOPIC ADD CONSTRAINT PK_SYSLOG_IDENT PRIMARY KEY (DTO_IDENT);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SYSLOG_QUEUE_DEL_TOPIC');

CREATE UNIQUE INDEX IDX_ORC_SQ_DELTOPIC_LOOKUP ON ORC_SYSLOG_QUEUE_DEL_TOPIC(DTO_NODEID, DTO_QUEUE_TYPE, DTO_GLOBAL, DTO_TOPIC, DTO_DELETETOKEN);

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-3_LTA::akn::(Checksum: 6:d6f9ac2f7f060a7db618c17812715c73)
CREATE TABLE ORC_LTA_MESSAGE_DATA (MES_MESSAGE_ID VARCHAR(255) NOT NULL, MES_ARCHIVE_TIME TIMESTAMP NOT NULL, MES_PROPS BLOB NOT NULL, MES_CONTENT BLOB);

ALTER TABLE ORC_LTA_MESSAGE_DATA ADD CONSTRAINT PK_LTA_MSGDATA_ID PRIMARY KEY (MES_MESSAGE_ID);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_LTA_MESSAGE_DATA');

CREATE TABLE ORC_LTA_MESSAGE_PAGE (MPA_MESSAGE_ID VARCHAR(255) NOT NULL, MPA_ID INTEGER NOT NULL, MPA_PAGE_TYPE INTEGER NOT NULL, MPA_ARCHIVE_TIME TIMESTAMP NOT NULL, MPA_DATA BLOB NOT NULL);

ALTER TABLE ORC_LTA_MESSAGE_PAGE ADD CONSTRAINT PK_LTA_MSG_PAGE PRIMARY KEY (MPA_MESSAGE_ID, MPA_ID, MPA_PAGE_TYPE);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_LTA_MESSAGE_PAGE');

CREATE TABLE ORC_LTA_PROCESS_DATA (PRS_PROCESS_ID VARCHAR(255) NOT NULL, PRS_ARCHIVE_DATE TIMESTAMP NOT NULL, PRS_PROCESS_DATA BLOB NOT NULL);

ALTER TABLE ORC_LTA_PROCESS_DATA ADD CONSTRAINT PK_LTA_PRODATA_ID PRIMARY KEY (PRS_PROCESS_ID);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_LTA_PROCESS_DATA');

CREATE TABLE ORC_LTA_MESSAGE_LIST_DATA (MLI_IDENTIFIER VARCHAR(255) NOT NULL, MLI_ARCHIVE_TIME TIMESTAMP NOT NULL, MLI_DATA BLOB NOT NULL);

ALTER TABLE ORC_LTA_MESSAGE_LIST_DATA ADD CONSTRAINT PK_LTA_MSGLIST_ID PRIMARY KEY (MLI_IDENTIFIER);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_LTA_MESSAGE_LIST_DATA');

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-5_Index::akn::(Checksum: 6:ab1249e973e27a3b18511690c8f7c494)
ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP DROP PRIMARY KEY;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP ADD CONSTRAINT PK_MLP_ID_KEY_REF PRIMARY KEY (MLP_ID, MLP_REFERENCE, MLP_KEY);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST_ENTRY_PROP');

UPDATE ORC_CLUSTER_LOCK_STATE SET ORC_LOCK_SCENARIO = 'dummy' WHERE ORC_LOCK_SCENARIO IS NULL;

ALTER TABLE ORC_CLUSTER_LOCK_STATE ALTER COLUMN  ORC_LOCK_SCENARIO SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_CLUSTER_LOCK_STATE');

UPDATE ORC_CLUSTER_LOCK_STATE SET ORC_LOCK_NAME = 'dummy' WHERE ORC_LOCK_NAME IS NULL;

ALTER TABLE ORC_CLUSTER_LOCK_STATE ALTER COLUMN  ORC_LOCK_NAME SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_CLUSTER_LOCK_STATE');

UPDATE ORC_CLUSTER_LOCK_STATE SET ORC_LOCK_OWNER = 'dummy' WHERE ORC_LOCK_OWNER IS NULL;

ALTER TABLE ORC_CLUSTER_LOCK_STATE ALTER COLUMN  ORC_LOCK_OWNER SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_CLUSTER_LOCK_STATE');

ALTER TABLE ORC_CLUSTER_LOCK_STATE ADD CONSTRAINT PK_CLUST_LOCK_STAT PRIMARY KEY (ORC_LOCK_SCENARIO, ORC_LOCK_NAME, ORC_LOCK_OWNER);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_CLUSTER_LOCK_STATE');

CREATE INDEX IDX_ORC_EVENT_SOURCE ON ORC_EVENT_SYSTEM(EVT_SOURCE, EVT_DESCRIPTION);

DROP INDEX IDX_ORC_MESSAGE_CREATED_AT;

CREATE INDEX IDX_ORC_MESSAGE_CREATED_AT ON ORC_MESSAGE(MES_TOUCHED, MES_CREATED_AT);

CREATE INDEX IDX_TRANSACTION_STATE ON ORC_TRANSACTION(TRA_STATE);

DROP INDEX IDX_ORC_MESSAGE_LIST_LEASETIME;

CREATE INDEX IDX_ORC_MESSAGE_LIST_LEASETIME ON ORC_MESSAGE_LIST(MLI_TYPE, MLI_TOUCHED, MLI_LEASE_TIME);

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-6::akn::(Checksum: 6:383b34e18fb458d629da1d867fe782e0)
DROP INDEX IDX_TOPIC_QUEUE_TOPIC_ID;

CREATE INDEX IDX_TOPIC_QUEUE_TOPIC_ID ON ORC_TOPIC_QUEUE(ORC_TOPIC_ID, QUEUE_TYPE, STATE, TARGET_NODE, ID);

