
create table ORC_SEQUENCE_COUNTER
(
	SCO_CATEGORY	varchar2(32),
	SCO_COUNTER		number(10)
);

CREATE TABLE ORC_PROCESS_FIFO_SCHEDULE
(
  PFS_ID                 VARCHAR2(30 BYTE)      NOT NULL,
  PFS_SCENARIO           VARCHAR2(256 BYTE)     NOT NULL,
  PFS_MODELL_REFERENCE   VARCHAR2(256 BYTE)     NOT NULL,
  PFS_PROCESS_REFERENCE  VARCHAR2(256 BYTE)     NOT NULL,
  PFS_TOKEN_REFERENCE    VARCHAR2(256 BYTE)     NOT NULL,
  PFS_VARIABLES          BLOB,
  PFS_TARGET_NODE        VARCHAR2(256 BYTE),
  PFS_STATE              VARCHAR2(10 BYTE)      NOT NULL
);

insert into ORC_SEQUENCE_COUNTER( SCO_CATEGORY, SCO_COUNTER) values ( 'FIFO.QUEUE', 0 );
commit;

alter table ORC_WORK_QUEUE add QUEUE_TYPE varchar2(1);

alter table ORC_BUSINESS_TRANSACTION add OBT_APPLICATION_STATE varchar2(30);
