/* ORACLE - Script 42 (V4.3.4.5) */

/* Add Index */

CREATE INDEX IDX_MSG_REFERRER_MSGLIST_ID ON ORC_MESSAGE_REFERERS(MRE_MESSAGELIST_ID);

CREATE INDEX IDX_ORC_MSG_LIST_CREATED_AT ON ORC_MESSAGE_LIST(MLI_CREATED_AT);

COMMIT;