--- Oracle Update Script 45 (V4.3.4.11)

CREATE TABLE ORC_PROCESS_OVERVIEW (
  POV_SCENARIO VARCHAR2(255) NOT NULL,
  POV_RUNNING INTEGER NOT NULL,
  POV_PAUSED INTEGER NOT NULL,
  POV_ABORTED INTEGER NOT NULL,
  POV_FINISHED INTEGER NOT NULL,
  POV_WARNING INTEGER NOT NULL
);

ALTER TABLE ORC_PROCESS_OVERVIEW
 ADD CONSTRAINT PK_ORC_PROCESS_OVERVIEW
 PRIMARY KEY(POV_SCENARIO);

/* Change Index from Script 40 */

drop INDEX IDX_ORC_PROCESINST_STATE_ID;

ALTER TABLE ORC_PROCESSINSTANCE_STATE ADD CONSTRAINT PK_PROCESSINSTANCE_STATE PRIMARY KEY (PRS_ID);

COMMIT;
