-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.7.0.0.xml
-- Ran at: 7/5/17 11:31 AM
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-1::akn::(Checksum: 6:0b3d233300c07781ba3aa99d28bc503f)
ALTER TABLE ORC_EVENT_PROCESS_TOKEN MODIFY EVT_ORCHESTRA_LINK VARCHAR2(300);

ALTER TABLE ORC_WORKLIST_TYPE ADD WLT_LABEL VARCHAR2(20);

ALTER TABLE ORC_EVENT_PROCESS_TOKEN ADD EVT_VARLOG BLOB;

ALTER TABLE ORC_EVENT_PROCESS_TOKEN ADD EVT_USE_VARLOG INTEGER;

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-2_Syslog::akn::(Checksum: 6:33e2b135c537d581771a0e7db4e8ba1b)
CREATE TABLE ORC_SYSLOG_QUEUE (ITEMTYPE VARCHAR2(256) NOT NULL, DISCRIMINATOR VARCHAR2(256) NOT NULL, CREATEDAT TIMESTAMP DEFAULT SYSDATE NOT NULL, WORKOBJECT BLOB, ID VARCHAR2(50) NOT NULL, ACTION CHAR(1) DEFAULT 'W', NAME VARCHAR2(256), STATE INTEGER, TARGET_NODE VARCHAR2(255), NODE_TICK VARCHAR2(255), QUEUE_TYPE VARCHAR2(1), PRIORITY INTEGER, ORC_TOPIC_OWNER VARCHAR2(256), ORC_TOPIC_ID VARCHAR2(256), NEXT_SCHEDULE_TIME TIMESTAMP, DELETETOKEN INTEGER);

ALTER TABLE ORC_SYSLOG_QUEUE ADD CONSTRAINT PK_SYSLOG_ID PRIMARY KEY (ID);

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_TOPIC_ID ON ORC_SYSLOG_QUEUE(ORC_TOPIC_ID, QUEUE_TYPE, STATE);

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_TOPIC_OWNER ON ORC_SYSLOG_QUEUE(ORC_TOPIC_OWNER, QUEUE_TYPE, STATE);

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_STATE_TYPE_ID ON ORC_SYSLOG_QUEUE(STATE, QUEUE_TYPE, ID);

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_S_T_Q_N ON ORC_SYSLOG_QUEUE(STATE, ORC_TOPIC_ID, TARGET_NODE, QUEUE_TYPE, NEXT_SCHEDULE_TIME);

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_STAT_TYP_PRIO ON ORC_SYSLOG_QUEUE(STATE, QUEUE_TYPE, PRIORITY, ID);

CREATE TABLE ORC_SYSLOG_QUEUE_DEL_TOPIC (DTO_TOPIC VARCHAR2(256) NOT NULL, DTO_DELETETOKEN INTEGER NOT NULL, DTO_GLOBAL INTEGER NOT NULL, DTO_NODEID VARCHAR2(32) NOT NULL, DTO_IDENT INTEGER NOT NULL, DTO_QUEUE_TYPE VARCHAR2(1) NOT NULL);

ALTER TABLE ORC_SYSLOG_QUEUE_DEL_TOPIC ADD CONSTRAINT PK_SYSLOG_IDENT PRIMARY KEY (DTO_IDENT);

CREATE UNIQUE INDEX IDX_ORC_SQ_DELTOPIC_LOOKUP ON ORC_SYSLOG_QUEUE_DEL_TOPIC(DTO_NODEID, DTO_QUEUE_TYPE, DTO_GLOBAL, DTO_TOPIC, DTO_DELETETOKEN);

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-3_LTA::akn::(Checksum: 6:d6f9ac2f7f060a7db618c17812715c73)
CREATE TABLE ORC_LTA_MESSAGE_DATA (MES_MESSAGE_ID VARCHAR2(255) NOT NULL, MES_ARCHIVE_TIME TIMESTAMP NOT NULL, MES_PROPS BLOB NOT NULL, MES_CONTENT BLOB);

ALTER TABLE ORC_LTA_MESSAGE_DATA ADD CONSTRAINT PK_LTA_MSGDATA_ID PRIMARY KEY (MES_MESSAGE_ID);

CREATE TABLE ORC_LTA_MESSAGE_PAGE (MPA_MESSAGE_ID VARCHAR2(255) NOT NULL, MPA_ID INTEGER NOT NULL, MPA_PAGE_TYPE INTEGER NOT NULL, MPA_ARCHIVE_TIME TIMESTAMP NOT NULL, MPA_DATA BLOB NOT NULL);

ALTER TABLE ORC_LTA_MESSAGE_PAGE ADD CONSTRAINT PK_LTA_MSG_PAGE PRIMARY KEY (MPA_MESSAGE_ID, MPA_ID, MPA_PAGE_TYPE);

CREATE TABLE ORC_LTA_PROCESS_DATA (PRS_PROCESS_ID VARCHAR2(255) NOT NULL, PRS_ARCHIVE_DATE TIMESTAMP NOT NULL, PRS_PROCESS_DATA BLOB NOT NULL);

ALTER TABLE ORC_LTA_PROCESS_DATA ADD CONSTRAINT PK_LTA_PRODATA_ID PRIMARY KEY (PRS_PROCESS_ID);

CREATE TABLE ORC_LTA_MESSAGE_LIST_DATA (MLI_IDENTIFIER VARCHAR2(255) NOT NULL, MLI_ARCHIVE_TIME TIMESTAMP NOT NULL, MLI_DATA BLOB NOT NULL);

ALTER TABLE ORC_LTA_MESSAGE_LIST_DATA ADD CONSTRAINT PK_LTA_MSGLIST_ID PRIMARY KEY (MLI_IDENTIFIER);

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-5_Index::akn::(Checksum: 6:ab1249e973e27a3b18511690c8f7c494)
ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP DROP PRIMARY KEY DROP INDEX;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP ADD CONSTRAINT PK_MLP_ID_KEY_REF PRIMARY KEY (MLP_ID, MLP_REFERENCE, MLP_KEY);

CREATE INDEX IDX_CLUST_LOCK_STAT ON ORC_CLUSTER_LOCK_STATE(ORC_LOCK_SCENARIO, ORC_LOCK_NAME, ORC_LOCK_OWNER);

CREATE INDEX IDX_ORC_EVENT_SOURCE ON ORC_EVENT_SYSTEM(EVT_SOURCE, EVT_DESCRIPTION);

DROP INDEX IDX_ORC_MESSAGE_CREATED_AT;

CREATE INDEX IDX_ORC_MESSAGE_CREATED_AT ON ORC_MESSAGE(MES_TOUCHED, MES_CREATED_AT);

CREATE INDEX IDX_TRANSACTION_STATE ON ORC_TRANSACTION(TRA_STATE);

DROP INDEX IDX_ORC_MESSAGE_LIST_LEASETIME;

CREATE INDEX IDX_ORC_MESSAGE_LIST_LEASETIME ON ORC_MESSAGE_LIST(MLI_TYPE, MLI_TOUCHED, MLI_LEASE_TIME);

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-6::akn::(Checksum: 6:383b34e18fb458d629da1d867fe782e0)
DROP INDEX IDX_TOPIC_QUEUE_TOPIC_ID;

CREATE INDEX IDX_TOPIC_QUEUE_TOPIC_ID ON ORC_TOPIC_QUEUE(ORC_TOPIC_ID, QUEUE_TYPE, STATE, TARGET_NODE, ID);

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-7_Index::akn::(Checksum: 6:ce7f525b9cabff9bc0d94b1ebbb4982e)
UPDATE ORC_ESB_SIGNAL_STATE SET EST_IDENTIFIER = 'dummy' WHERE EST_IDENTIFIER IS NULL;

ALTER TABLE ORC_ESB_SIGNAL_STATE MODIFY EST_IDENTIFIER NOT NULL;

ALTER TABLE ORC_ESB_SIGNAL_STATE ADD CONSTRAINT PK_ORC_ESB_SIGSTA PRIMARY KEY (EST_IDENTIFIER);

COMMIT;

