ALTER TABLE ORC_MONITOR_SETTINGS
ADD COLUMN ORC_MESSAGEPANEL_ACTIVE        integer
ADD COLUMN ORC_MESSAGEPANEL_TRESHOLD      integer
ADD COLUMN ORC_MESSAGEPANEL_VISIBLETIME   integer
ADD COLUMN ORC_THEME                      VARCHAR(255);

ALTER TABLE ORC_MONITOR_SETTINGS DROP COLUMN ORC_LOGOFF_PERIODE;

update ORC_MONITOR_SETTINGS set ORC_MESSAGEPANEL_ACTIVE = 1
 where ORC_MESSAGEPANEL_ACTIVE is null;

update ORC_MONITOR_SETTINGS set ORC_MESSAGEPANEL_TRESHOLD = 10
 where ORC_MESSAGEPANEL_TRESHOLD is null;

update ORC_MONITOR_SETTINGS set ORC_MESSAGEPANEL_VISIBLETIME = 10000
 where ORC_MESSAGEPANEL_VISIBLETIME is null;
 
update ORC_MONITOR_SETTINGS set ORC_THEME = 'standard'
 where ORC_THEME is null;

commit;

CREATE TABLE ORC_PROCESS_EXECUTION
(
  ORC_PROCESS_MODEL           VARCHAR(255) NOT NULL,
  ORC_SCENARIO_ID             VARCHAR(255),
  ORC_TOTAL_PROCESS_COUNT     BIGINT,
  ORC_TOTAL_PROCESS_DURATION  BIGINT,
  ORC_FIRST_RUN               TIMESTAMP,
  ORC_LAST_RUN                TIMESTAMP,
  ORC_MIN_DURATION            BIGINT,
  ORC_MAX_DURATION            BIGINT
);


CREATE TABLE ORC_SERVER_SETTINGS
(
  ID              VARCHAR(255),
  LOGOUT_PERIODE  integer,
  LOGLEVEL        VARCHAR(255)
);

ALTER TABLE ORC_PROCESS_EXECUTION ADD PRIMARY KEY(ORC_PROCESS_MODEL);












ALTER TABLE ORC_SERVER_SETTINGS ALTER COLUMN ID SET NOT NULL;
CALL sysproc.admin_cmd ('REORG TABLE ORC_SERVER_SETTINGS');
ALTER TABLE ORC_SERVER_SETTINGS ADD PRIMARY KEY(ID);
CALL sysproc.admin_cmd ('REORG TABLE ORC_SERVER_SETTINGS');

CALL sysproc.admin_cmd ('REORG TABLE ORC_MONITOR_SETTINGS');
ALTER TABLE ORC_MONITOR_SETTINGS ADD PRIMARY KEY(ORC_USERID);
CALL sysproc.admin_cmd ('REORG TABLE ORC_MONITOR_SETTINGS');

ALTER TABLE ORC_MONITOR_TABLESETTINGS ADD PRIMARY KEY(ORC_PARENT_USERID,ORC_TABLECLASS);

INSERT INTO ORC_SEC_ROLE_V2(OSR_SCENARIO, OSR_IDENTIFIER, OSR_DESC) VALUES ('RUNTIME', 'RUNTIME:ServerAdministrator', NULL);
INSERT INTO ORC_SEC_ROLE_V2(OSR_SCENARIO, OSR_IDENTIFIER, OSR_DESC) VALUES ('RUNTIME', 'RUNTIME:Remote.Administrator', NULL);

INSERT INTO ORC_SEC_USER_ROLES_V2(OUR_USER_ID, OUR_ROLE_ID) VALUES ('RUNTIME:admin', 'ServerAdministrator');



commit;

ALTER TABLE ORC_WORK_QUEUE ADD PRIORITY integer default 0 not null;
