












alter table ORC_QUEUE_TOPIC_STATE add QTS_GROUP VARCHAR(255);

COMMIT;


drop INDEX IDX_WORK_QUEUE_TOPIC_ID;

create index IDX_WORK_QUEUE_TOPIC_ID on ORC_WORK_QUEUE(ORC_TOPIC_ID, QUEUE_TYPE, STATE);

drop INDEX IDX_WORK_QUEUE_TOPIC_OWNER; 

create index IDX_WORK_QUEUE_TOPIC_OWNER on ORC_WORK_QUEUE(ORC_TOPIC_OWNER, QUEUE_TYPE, STATE);


create index IDX_WORK_QUEUE_STATE_TYPE_ID on ORC_WORK_QUEUE(STATE, QUEUE_TYPE, ID);

create index IDX_WORK_QUEUE_STAT_TYP_PRIO on ORC_WORK_QUEUE(STATE, QUEUE_TYPE, PRIORITY desc, ID);

COMMIT;


CREATE TABLE ORC_TOPIC_QUEUE (
  ITEMTYPE 		VARCHAR(256) NOT NULL,
  DISCRIMINATOR VARCHAR(256) NOT NULL,
  CREATEDAT 	TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
  WORKOBJECT 	BLOB,
  ID 			VARCHAR(30) NOT NULL,
  ACTION 		char(1) DEFAULT 'W',
  NAME 			VARCHAR(256),
  STATE 		INTEGER,
  cluster_node 	VARCHAR(255),
  target_node 	VARCHAR(255),
  node_tick 	VARCHAR(255),
  QUEUE_TYPE 	VARCHAR(1),
  PRIORITY 		INTEGER,
  ORC_TOPIC_OWNER VARCHAR(256),
  ORC_TOPIC_ID	 VARCHAR(256),
  constraint PK_TOPIC_QUEUE PRIMARY KEY (ID)
);

create index IDX_TOPIC_QUEUE_TOPIC_ID on ORC_TOPIC_QUEUE(ORC_TOPIC_ID, QUEUE_TYPE, STATE);

create index IDX_TOPIC_QUEUE_TOPIC_OWNER on ORC_TOPIC_QUEUE(ORC_TOPIC_OWNER, QUEUE_TYPE, STATE);

create index IDX_TOPIC_QUEUE_STATE_TYPE_ID on ORC_TOPIC_QUEUE(STATE, QUEUE_TYPE, ID);

create index IDX_TOPIC_QUEUE_STAT_TYP_PRIO on ORC_TOPIC_QUEUE(STATE, QUEUE_TYPE, PRIORITY, ID);

COMMIT;



CREATE TABLE ORC_EXT_ARCHIVE (
  EXA_ID BIGINT NOT NULL,
  EXA_REQ_MSG_ID VARCHAR(256),
  EXA_REQ_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP NOT NULL,
  EXA_REQ_PROPERTY_1 VARCHAR(255),
  EXA_REQ_PROPERTY_2 VARCHAR(255),
  EXA_REQ_PROPERTY_3 VARCHAR(255),
  EXA_REQ_CONTENT BLOB,
  EXA_RESP_TIMESTAMP TIMESTAMP,
  EXA_RESP_PROPERTY_1 VARCHAR(255),
  EXA_RESP_PROPERTY_2 VARCHAR(255),
  EXA_RESP_PROPERTY_3 VARCHAR(255),
  EXA_RESP_CONTENT BLOB,
  EXA_TECHNICAL_SOURCE VARCHAR(255),
  EXA_TECHNICAL_NAME VARCHAR(255),
  EXA_RESP_MSG_ID VARCHAR(255),
  constraint PK_EXT_ARCHIVE PRIMARY KEY (EXA_ID)
);


CREATE TABLE ORC_EXT_ARCHIVE_ERROR (
  EAE_ARC_ID BIGINT NOT NULL,
  ERC_EXC_TYPE VARCHAR(255),
  ERC_ACTION VARCHAR(255),
  ERC_MESSAGE VARCHAR(255),
  ERC_CLASSNAME VARCHAR(255),
  ERC_METHOD VARCHAR(255),
  ERC_FILE VARCHAR(255),
  ERC_LINE INTEGER,
  ERC_STACK BLOB,
  ERC_ROLE VARCHAR(255),
  constraint PK_EXT_ARCH_ERR PRIMARY KEY (EAE_ARC_ID)
);

COMMIT;

insert into ORC_SEQUENCE_COUNTER( sco_category, sco_counter ) 
  values ( 'EXT.ARCHIVE', 1 );

update ORC_MONITOR_TABLESETTINGS set ORC_COLUMN_PATTERN = CONCAT(ORC_COLUMN_PATTERN, ',y') where ORC_TABLECLASS = 'ProcessOverviewTable';

update ORC_MONITOR_TABLESETTINGS 
   set ORC_COLUMN_PATTERN = concat(ORC_COLUMN_PATTERN, ',y')
 where ORC_TABLECLASS = 'ProcessOverviewTable'
   and TRANSLATE(ORC_COLUMN_PATTERN, 'y', 'n') = 'y,y,y,y,y,y,y';

COMMIT;
