ALTER TABLE ORC_PROCESS_STATE ADD PRS_PROCESS_MODEL VARCHAR(255);

create table ORC_PROCESS_RUNTIME_STATE (
	PRS_ID VARCHAR(255) not null, 
	PRS_START_EVENT INTEGER, 
	PRS_STATE INTEGER, 
	PRS_VARIABLES BLOB, 
	PRS_PROCESS VARCHAR(255), 
	PRS_PROCESSMODELL VARCHAR(255), 
	PRS_NODE_ID VARCHAR(255), 
	constraint PK_ORC_PR_RT_ST PRIMARY KEY (PRS_ID)
);

ALTER TABLE ORC_MONITOR_SETTINGS ADD ORC_STAGE_LABEL_SIZE INTEGER;
ALTER TABLE ORC_MONITOR_SETTINGS ADD ORC_STAGE_LABEL_X INTEGER;
ALTER TABLE ORC_MONITOR_SETTINGS ADD ORC_STAGE_LABEL_Y INTEGER;

update ORC_MONITOR_SETTINGS set ORC_STAGE_LABEL_SIZE = 30, ORC_STAGE_LABEL_X = -1, ORC_STAGE_LABEL_Y = -1; 

insert into ORC_SEC_ROLE_V2 (OSR_SCENARIO,OSR_IDENTIFIER,OSR_DESC) values ('RUNTIME','RUNTIME:Scenario.Activate',null);
insert into ORC_SEC_ROLE_V2 (OSR_SCENARIO,OSR_IDENTIFIER,OSR_DESC) values ('RUNTIME','RUNTIME:Scenario.Deactivate',null);
insert into ORC_SEC_ROLE_V2 (OSR_SCENARIO,OSR_IDENTIFIER,OSR_DESC) values ('RUNTIME','RUNTIME:Adapter.Activate',null);
insert into ORC_SEC_ROLE_V2 (OSR_SCENARIO,OSR_IDENTIFIER,OSR_DESC) values ('RUNTIME','RUNTIME:Adapter.Deactivate',null);

insert into ORC_SEC_GROUP_ROLES_V2 (OGR_GROUP_ID,OGR_ROLE_ID) values ('RUNTIME:Adapter','Adapter.Deactivate');
insert into ORC_SEC_GROUP_ROLES_V2 (OGR_GROUP_ID,OGR_ROLE_ID) values ('RUNTIME:Adapter','Adapter.Activate');
insert into ORC_SEC_GROUP_ROLES_V2 (OGR_GROUP_ID,OGR_ROLE_ID) values ('RUNTIME:Deployment','Scenario.Deactivate');
insert into ORC_SEC_GROUP_ROLES_V2 (OGR_GROUP_ID,OGR_ROLE_ID) values ('RUNTIME:Deployment','Scenario.Activate');

insert into ORC_SEC_USER_ROLES_V2 (OUR_USER_ID,OUR_ROLE_ID) values ('RUNTIME:admin','Adapter.Deactivate');
insert into ORC_SEC_USER_ROLES_V2 (OUR_USER_ID,OUR_ROLE_ID) values ('RUNTIME:admin','Adapter.Activate');
insert into ORC_SEC_USER_ROLES_V2 (OUR_USER_ID,OUR_ROLE_ID) values ('RUNTIME:admin','Scenario.Deactivate');
insert into ORC_SEC_USER_ROLES_V2 (OUR_USER_ID,OUR_ROLE_ID) values ('RUNTIME:admin','Scenario.Activate');

commit;

CREATE TABLE orc_process_ext_business_keys (
  PEK_PROCESS_ID VARCHAR(255) NOT NULL,
  PEK_BUSINESS_KEY VARCHAR(255) DEFAULT NULL,
  PEK_BUSINESS_KEY_NAME VARCHAR(255) NOT NULL,
  constraint PK_ORC_PR_EXT_BK PRIMARY KEY (PEK_PROCESS_ID,PEK_BUSINESS_KEY_NAME)
);

insert into orc_process_ext_business_keys(PEK_PROCESS_ID,PEK_BUSINESS_KEY,PEK_BUSINESS_KEY_NAME)
select PRS_PROCESS_ID, PRS_BUSINESS_KEY, PRS_BUSINESS_KEY_NAME 
  from ORC_PROCESS_STATE where PRS_BUSINESS_KEY_NAME is not null;

update orc_process_state 
   set PRS_BUSINESS_KEY = PRS_BUSINESS_KEY_NAME || ': ' || PRS_BUSINESS_KEY 
 where PRS_BUSINESS_KEY_NAME is not null;

ALTER TABLE ORC_PROCESS_STATE DROP PRS_BUSINESS_KEY_NAME;
ALTER TABLE ORC_PROCESS_STATE ALTER COLUMN PRS_BUSINESS_KEY SET DATA TYPE VARCHAR(1024);

ALTER TABLE orc_work_queue DROP cluster_node;

alter table orc_queue_topic_state add QTS_NODE_ID VARCHAR(255) DEFAULT 'ORC';

ALTER TABLE orc_topic_queue DROP cluster_node;

ALTER TABLE orc_esb_topic_state ADD ETS_NODE_ID VARCHAR(255);

insert into orc_cluster_lock(ORC_LOCK_NAME,ORC_LOCK_SCENARIO) values('KPIDATA','GLOBAL');

DROP INDEX UIDX_ORC_XML_SCHEMA;

CREATE INDEX IDX_ORC_XML_SCHEMA ON ORC_XML_SCHEMA(XSC_NAME, XSC_SCENARIO);

DROP INDEX UIDX_ORC_MESSAGE_TYPE;


CREATE INDEX IDX_ORC_PR_RT_STATE ON ORC_PROCESS_RUNTIME_STATE(PRS_PROCESS,PRS_STATE);

CREATE INDEX IDX_ORC_PR_FP_MODEL ON ORC_PROCESS_RUNTIME_STATE(PRS_PROCESSMODELL);

update orc_esb_topic_state 
   set ETS_IDENTIFIER = substr( ETS_IDENTIFIER, 39 );
   
update orc_esb_topic_state
   set ETS_OWNER = substr(ETS_IDENTIFIER,2, POSSTR( ETS_IDENTIFIER, '}' ) -2 );
   
update ORC_QUEUE_TOPIC_STATE
   set QTS_IDENTIFIER = substr( QTS_IDENTIFIER, 11, POSSTR( QTS_IDENTIFIER, '[' ) - 12 )
 where QTS_GROUP = 'topic';
   
update ORC_QUEUE_TOPIC_STATE
   set QTS_OWNER = substr(QTS_IDENTIFIER,2, POSSTR( QTS_IDENTIFIER, '}') - 2 )
 where QTS_GROUP = 'topic';
 
update ORC_TOPIC_QUEUE 
   set ORC_TOPIC_ID = substr( ORC_TOPIC_ID, 11, POSSTR( ORC_TOPIC_ID, '[' ) - 12 );
    
update ORC_TOPIC_QUEUE 
   set ORC_TOPIC_OWNER = substr(ORC_TOPIC_ID,2, POSSTR( ORC_TOPIC_ID, '}') - 2 );

CALL sysproc.admin_cmd ('REORG TABLE ORC_TOPIC_QUEUE');
CALL sysproc.admin_cmd ('REORG TABLE ORC_QUEUE_TOPIC_STATE');
CALL sysproc.admin_cmd ('REORG TABLE ORC_WORK_QUEUE');
CALL sysproc.admin_cmd ('REORG TABLE ORC_ESB_TOPIC_STATE');
CALL sysproc.admin_cmd ('REORG TABLE ORC_PROCESS_STATE');
CALL sysproc.admin_cmd ('REORG TABLE ORC_MONITOR_SETTINGS');

CREATE INDEX IDX_ORC_WORK_QUEUE_2 ON ORC_WORK_QUEUE(ID,NODE_TICK,TARGET_NODE);
   
commit;
