alter table ORC_QUEUE_TOPIC_STATE drop constraint PK_QUE_TOPIC_STATE;

ALTER TABLE ORC_QUEUE_TOPIC_STATE ALTER COLUMN QTS_NODE_ID SET NOT NULL;
CALL sysproc.admin_cmd ('REORG TABLE ORC_QUEUE_TOPIC_STATE');

ALTER TABLE ORC_QUEUE_TOPIC_STATE ADD CONSTRAINT PK_QUE_TOPIC_STATE PRIMARY KEY(QTS_IDENTIFIER,QTS_NODE_ID);

ALTER TABLE ORC_ADAPTER_STATE DROP PRIMARY KEY;
ALTER TABLE ORC_ADAPTER_STATE ALTER COLUMN ADS_NODE_ID SET NOT NULL;
CALL sysproc.admin_cmd ('REORG TABLE ORC_ADAPTER_STATE');  

ALTER TABLE ORC_ADAPTER_STATE
  ADD CONSTRAINT PK_ORC_ADAP_STATE PRIMARY KEY
    (ADS_ADAPTER_NAME, ADS_NODE_ID);


CALL sysproc.admin_cmd ('REORG TABLE ORC_QUEUE_TOPIC_STATE');
CALL sysproc.admin_cmd ('REORG TABLE ORC_ADAPTER_STATE');  
