
ALTER TABLE ORC_PROCESS_RUNTIME_STATE DROP CONSTRAINT PK_ORC_PR_RT_ST;

DROP INDEX IDX_ORC_PR_RT_STATE;

DROP INDEX IDX_ORC_PR_FP_MODEL;

ALTER TABLE ORC_PROCESS_RUNTIME_STATE ALTER COLUMN PRS_PROCESS SET NOT NULL;
CALL sysproc.admin_cmd ('REORG TABLE ORC_PROCESS_RUNTIME_STATE');

ALTER TABLE ORC_PROCESS_RUNTIME_STATE ADD CONSTRAINT PK_ORC_PR_RT_ST PRIMARY KEY(PRS_PROCESS);

CREATE INDEX IDX_ORC_PR_FP_MODEL ON ORC_PROCESS_RUNTIME_STATE(PRS_PROCESSMODELL, PRS_STATE, PRS_NODE_ID);

COMMIT;
