
CREATE TABLE ORC_XML_SCHEMA
(
  XSC_SCENARIO     VARCHAR(250),
  XSC_NAME         VARCHAR(250),
  XSC_DATA         IMAGE,
  XSC_DEPLOYED_AT  DATETIME,
  XSC_UNIQUE_NAME  VARCHAR(250) NOT NULL
);


CREATE UNIQUE INDEX PK_ORC_XML_SCHEMA ON ORC_XML_SCHEMA
(XSC_UNIQUE_NAME);


CREATE UNIQUE INDEX UIDX_ORC_XML_SCHEMA ON ORC_XML_SCHEMA
(XSC_NAME, XSC_SCENARIO);

GO
