
CREATE TABLE ORC_MESSAGE_LIST
(
  MLI_IS_SYSTEM   NUMERIC(1),
  MLI_AREA        VARCHAR(256),
  MLI_IDENTIFIER  VARCHAR(256),
  MLI_ID          NUMERIC(18)
);

CREATE TABLE ORC_MESSAGE_LIST_ENTRY
(
  MLE_INDEX        NUMERIC(10),
  MLE_MESSAGE_REF  VARCHAR(256),
  MLE_ID           NUMERIC(18)
);

CREATE TABLE ORC_MESSAGE_LIST_ENTRY_PROP
(
  MLP_INDEX  NUMERIC(10),
  MLP_KEY    VARCHAR(256),
  MLP_VALUE  VARCHAR(512),
  MLP_ID     NUMERIC(18)
);

insert into ORC_SEQUENCE_COUNTER(SCO_CATEGORY, SCO_COUNTER) values ('MESSAGELIST', 9);

CREATE TABLE ORC_SVC_DECLARATION
(
  SDC_SCENARIO     VARCHAR(250),
  SDC_NAME         VARCHAR(250),
  SDC_DATA         image,
  SDC_DEPLOYED_AT  DATETIME,
  SDC_UNIQUE_NAME  VARCHAR(250)
);

CREATE TABLE ORC_SVC_PROVIDER
(
  SPR_SCENARIO     VARCHAR(250),
  SPR_NAME         VARCHAR(250),
  SPR_DATA         image,
  SPR_DEPLOYED_AT  DATETIME,
  SPR_UNIQUE_NAME  VARCHAR(250)
);

















create table ORC_SEC_USER_PKCS12
(
	OUS_USER_ID 		VARCHAR(255) not null, 
	OUS_SCENARIO 		VARCHAR(255), 
	OUS_KEYPASSWORD 	VARCHAR(255), 
	OUS_STOREPASSWORD 	VARCHAR(255), 
	OUS_PKCS12STORE 	image, 
	primary key (OUS_USER_ID)
);

create table ORC_SEC_USER_SSH
(
	OUS_USER_ID 		VARCHAR(255) not null, 
	OUS_SCENARIO 		VARCHAR(255), 
	OUS_PASSWORD 		VARCHAR(255), 
	OUS_CERTIFICATE 	image, 
	primary key (OUS_USER_ID)
);

CREATE TABLE ORC_PRT_PARTNERCONFIG
(
	PRT_SCENARIO     	VARCHAR(250),
	PRT_NAME         	VARCHAR(250),
	PRT_DATA         	image,
	PRT_DEPLOYED_AT  	DATETIME,
	PRT_UNIQUE_NAME  	VARCHAR(250)
);

Insert into ORC_CLUSTER_LOCK (ORC_LOCK_NAME, ORC_LOCK_STATE, ORC_LOCK_OWNER, ORC_LOCK_SCENARIO) Values  ('MESSAGELIST', NULL, NULL, 'GLOBAL');

ALTER TABLE orc_recovery_data ALTER COLUMN RDA_TOKEN_ID VARCHAR(250);
