







ALTER TABLE ORC_SEC_USER_AUTH_METHODS_V2 ADD CONSTRAINT PK_SEC_USER_AUTH_METH2 PRIMARY KEY (OAM_USER_ID, OAM_METHOD);

ALTER TABLE ORC_SEC_USER_ROLES_V2 ADD CONSTRAINT PK_SEC_USER_ROLS2 PRIMARY KEY (OUR_USER_ID, OUR_ROLE_ID);

ALTER TABLE ORC_SEC_USER_GROUP_V2 ADD CONSTRAINT PK_SEC_USER_GRPS2 PRIMARY KEY (OUG_USER_ID, OUG_GROUP_ID);

ALTER TABLE ORC_SEC_GROUP_ROLES_V2 ADD CONSTRAINT PK_SEC_GROUP_ROLS2 PRIMARY KEY (OGR_GROUP_ID, OGR_ROLE_ID);

GO

