--- Update Script MS-SQL für V4.3.3.15 ----

EXEC sp_rename 'ORC_PROCESS_ARBORT.PRA_CHILD_PROCESS', 'PRA_PROCESSINSTANCE', 'COLUMN';
ALTER TABLE ORC_PROCESS_ARBORT
  ADD PRA_PROCSSMODELL VARCHAR(255)
GO

CREATE VIEW ORC_PROCESS_STATE_BUSINESS_KEY
	AS SELECT * FROM 
		ORC_PROCESS_STATE,
		ORC_PROCESS_EXT_BUSINESS_KEYS
	WHERE PEK_PROCESS_ID = PRS_PROCESS_ID
GO

CREATE INDEX IDX_ORC_PROCESS_STATE_1 ON ORC_PROCESS_STATE(PRS_SCENARIO_ID,PRS_STATE) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

CREATE INDEX IDX_ORC_PROCESS_STATE_2 ON ORC_PROCESS_STATE(PRS_SCENARIO_ID,PRS_MODELL_ID) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

CREATE INDEX IDX_ORC_PROCESS_EXT_BK ON ORC_PROCESS_EXT_BUSINESS_KEYS(PEK_BUSINESS_KEY_NAME,PEK_BUSINESS_KEY) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
GO
