
ALTER TABLE ORC_PROCESS_RUNTIME_STATE DROP CONSTRAINT PK_ORC_PR_RT_STATE;

DROP INDEX IDX_ORC_PR_FP_MODEL ON ORC_PROCESS_RUNTIME_STATE WITH ( ONLINE = OFF );

ALTER TABLE ORC_PROCESS_RUNTIME_STATE ALTER COLUMN PRS_PROCESS VARCHAR(255) NOT NULL;

ALTER TABLE ORC_PROCESS_RUNTIME_STATE ADD CONSTRAINT PK_ORC_PR_RT_STATE PRIMARY KEY (PRS_PROCESS);

CREATE INDEX IDX_ORC_PR_FP_MODEL ON ORC_PROCESS_RUNTIME_STATE(PRS_PROCESSMODELL, PRS_STATE, PRS_NODE_ID) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

GO
