
CREATE TABLE ORC_PROCESS_OVERVIEW (
  POV_SCENARIO VARCHAR(255) NOT NULL,
  POV_RUNNING BIGINT NOT NULL,
  POV_PAUSED BIGINT NOT NULL,
  POV_ABORTED BIGINT NOT NULL,
  POV_FINISHED BIGINT NOT NULL,
  POV_WARNING BIGINT NOT NULL
);

ALTER TABLE ORC_PROCESS_OVERVIEW SET (LOCK_ESCALATION = DISABLE);

ALTER TABLE ORC_PROCESS_OVERVIEW
 ADD CONSTRAINT PK_ORC_PROCESS_OVERVIEW PRIMARY KEY(POV_SCENARIO)
 WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

GO


/* Change Index from Script 36 */

ALTER TABLE ORC_PROCESS_RUNTIME_STATE DROP CONSTRAINT PK_ORC_PR_RT_STATE;

ALTER TABLE ORC_PROCESS_RUNTIME_STATE ADD CONSTRAINT PK_ORC_PR_RT_STATE PRIMARY KEY (PRS_PROCESS)
	  WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

GO

/* Change Index from Script 40 */

drop INDEX IDX_ORC_PROCESINST_STATE_ID ON ORC_PROCESSINSTANCE_STATE;

ALTER TABLE ORC_PROCESSINSTANCE_STATE ADD CONSTRAINT PK_PROCESSINSTANCE_STATE PRIMARY KEY (PRS_ID)
 WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

GO
