
ALTER TABLE ORC_PROCESS_FIFO_SCHEDULE 
  ADD CONSTRAINT PK_ORC_FIFO_SCHED_PK PRIMARY KEY (PFS_PROCESS_REFERENCE)
  WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS = OFF);
  
GO

DROP INDEX IDX_ORC_PROCESS_STATE_1 on ORC_PROCESS_STATE;

GO
