-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_master_4.5.0.0.xml
-- Ran at: 02.05.14 16:31
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-01::akn::(Checksum: 6:041d430e3bef5ac6e6f45a815fdd5780)
CREATE UNIQUE INDEX PK_ORC_SEC_ROLE_V2 ON [ORC_SEC_ROLE_V2]([OSR_SCENARIO], [OSR_IDENTIFIER]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-02::akn::(Checksum: 6:459af336b6d8574a377fdeddaa028ff2)
INSERT INTO [ORC_SEC_ROLE_V2] ([OSR_SCENARIO], [OSR_IDENTIFIER], [OSR_DESC]) VALUES ('RUNTIME', 'RUNTIME:Documentation.Scenario', 'Export scenario documentation')
GO

INSERT INTO [ORC_SEC_ROLE_V2] ([OSR_SCENARIO], [OSR_IDENTIFIER], [OSR_DESC]) VALUES ('RUNTIME', 'RUNTIME:Documentation.Server', 'Export complete server documentation including all scenarios')
GO

INSERT INTO [ORC_SEC_ROLE_V2] ([OSR_SCENARIO], [OSR_IDENTIFIER], [OSR_DESC]) VALUES ('RUNTIME', 'RUNTIME:Serverinfo.Details', '')
GO

INSERT INTO [ORC_SEC_USER_ROLES_V2] ([OUR_USER_ID], [OUR_ROLE_ID]) VALUES ('RUNTIME:admin', 'Documentation.Scenario')
GO

INSERT INTO [ORC_SEC_USER_ROLES_V2] ([OUR_USER_ID], [OUR_ROLE_ID]) VALUES ('RUNTIME:admin', 'Documentation.Server')
GO

INSERT INTO [ORC_SEC_USER_ROLES_V2] ([OUR_USER_ID], [OUR_ROLE_ID]) VALUES ('RUNTIME:admin', 'Serverinfo.Details')
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-03::akn::(Checksum: 6:63210542a13c8fa15ffbd5071bc27804)
CREATE TABLE [ORC_LOOKUPTABLE] ([LUT_SCENARIO] VARCHAR(250), [LUT_NAME] VARCHAR(250), [LUT_DATA] VARBINARY(MAX), [LUT_DEPLOYED_AT] datetime, [LUT_UNIQUE_NAME] VARCHAR(250) NOT NULL)
GO

CREATE TABLE [ORC_SCENARIO_DOC] ([SDO_SCENARIO] VARCHAR(250), [SDO_NAME] VARCHAR(250), [SDO_DATA] VARBINARY(MAX), [SDO_DEPLOYED_AT] datetime)
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-04::akn::(Checksum: 6:42ddc9bd4580dd3abea6ad388df46c0f)
ALTER TABLE [ORC_PROCESS_SCENARIO] ADD [PSC_SUSPEND_STATE] INT
GO

ALTER TABLE [ORC_PROCESS_SCENARIO] ADD [PSC_COMMENT] VARCHAR(255)
GO

UPDATE [ORC_PROCESS_SCENARIO] SET [PSC_SUSPEND_STATE] = 0
GO

ALTER TABLE [ORC_PROCESS_SCENARIO_HISTORY] ADD [PSC_COMMENT] VARCHAR(255)
GO

ALTER TABLE [ORC_PROCESSINSTANCE_STATE] ADD [PRS_MODE] SMALLINT NOT NULL CONSTRAINT DF_ORC_PROCESSINSTANCE_STATE_PRS_MODE DEFAULT 0
GO

ALTER TABLE [ORC_MONITOR_SETTINGS] ADD [ORC_START_PAGE_PRESET] VARCHAR(255)
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-05::akn::(Checksum: 6:f8f27eca6f8380e4565deb23913a0aa4)
CREATE TABLE [ORC_ALERT_DATA] ([CHANGED_AT] datetime NOT NULL, [DATA] VARBINARY(MAX))
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-06::akn::(Checksum: 6:f91b33d2bcb5cdd9f54a113d635c5d3c)
CREATE TABLE [ORC_BUSINESS_CALENDAR] ([BCAL_ID] VARCHAR(255) NOT NULL, [BCAL_NAME] VARCHAR(255), [BCAL_DESC] VARCHAR(255), CONSTRAINT [PK_BCAL_ID] PRIMARY KEY ([BCAL_ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF))
GO

CREATE TABLE [ORC_BUSINESS_CALENDAR_ENTRY] ([BCE_ID] VARCHAR(255) NOT NULL, [BCE_TYPE] VARCHAR(100) NOT NULL, [BCE_NAME] VARCHAR(255), [BCE_DESCRIPTION] VARCHAR(255), [BCE_FIXEDDAY] datetime, [BCE_START_DAY] datetime, [BCE_END_DAY] datetime, [BCE_OFFSET] INT, [BCE_TIMESPAN_TYPE] VARCHAR(32), [BCE_TIMESPAN_VALUE] INT, [BCAL] VARCHAR(255) NOT NULL, CONSTRAINT [PK_BCE_ID] PRIMARY KEY ([BCE_ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF), CONSTRAINT [FK_CALENDAR_PARENT] FOREIGN KEY ([BCAL]) REFERENCES dbo.ORC_BUSINESS_CALENDAR (BCAL_ID))
GO

CREATE INDEX BCAL_PARENT_IDX ON [ORC_BUSINESS_CALENDAR_ENTRY]([BCAL]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

INSERT INTO [ORC_SEC_ROLE_V2] ([OSR_SCENARIO], [OSR_IDENTIFIER], [OSR_DESC]) VALUES ('RUNTIME', 'RUNTIME:BusinessCalendar', '')
GO

INSERT INTO [ORC_SEC_USER_ROLES_V2] ([OUR_USER_ID], [OUR_ROLE_ID]) VALUES ('RUNTIME:admin', 'BusinessCalendar')
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-07::akn::(Checksum: 6:fa2151ff8c9ea318a79c8cc3510b12bd)
DROP INDEX [ORC_PROCESS_STATE].IDX_ORC_PROCESS_STATE_2
GO

CREATE INDEX IDX_ORC_PROCESS_STATE_2 ON [ORC_PROCESS_STATE]([PRS_SCENARIO_ID], [PRS_MODELL_ID], [PRS_STATE]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-08::akn::(Checksum: 6:5b0c6248146c958384132ad8b420b11b)
CREATE TABLE [ORC_PROCESS_FIFO_SCHED_CACHE] ([PFC_ID] VARCHAR(50) NOT NULL, [PFC_SCENARIO] VARCHAR(256) NOT NULL, [PFC_MODELL_REFERENCE] VARCHAR(256) NOT NULL, [PFC_PROCESS_REFERENCE] VARCHAR(256) NOT NULL, [PFC_VARIABLES] VARBINARY(MAX), [PFC_TARGET_NODE] VARCHAR(256), CONSTRAINT [PK_PROCESS_FIFO_CACHE] PRIMARY KEY ([PFC_ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF))
GO

CREATE INDEX IDX_PROCESS_FIFO_CACHE ON [ORC_PROCESS_FIFO_SCHED_CACHE]([PFC_MODELL_REFERENCE]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-09::akn::(Checksum: 6:9fc886f7a9027b335b4b04227a4f2f4c)
INSERT INTO [ORC_SEC_ROLE_V2] ([OSR_SCENARIO], [OSR_IDENTIFIER], [OSR_DESC]) VALUES ('RUNTIME', 'RUNTIME:AlertSystem.View', '')
GO

INSERT INTO [ORC_SEC_ROLE_V2] ([OSR_SCENARIO], [OSR_IDENTIFIER], [OSR_DESC]) VALUES ('RUNTIME', 'RUNTIME:AlertSystem.Modify', '')
GO

INSERT INTO [ORC_SEC_USER_ROLES_V2] ([OUR_USER_ID], [OUR_ROLE_ID]) VALUES ('RUNTIME:admin', 'AlertSystem.View')
GO

INSERT INTO [ORC_SEC_USER_ROLES_V2] ([OUR_USER_ID], [OUR_ROLE_ID]) VALUES ('RUNTIME:admin', 'AlertSystem.Modify')
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-10::akn::(Checksum: 6:e88a64af0d528abeab55e7d4d9d2175c)
UPDATE [ORC_KPI_INSTANCE] SET [KIN_CLASS_IDENT] = 'SIGNAL.' + SUBSTRING(KIN_CLASS_IDENT, 7, 50) WHERE KIN_CLASS_IDENT like 'TOPIC.%'
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-11::akn::(Checksum: 6:e6baa112eada4899873a0fcf4e4d7092)
CREATE VIEW [ORC_PROCESS_STATE_MONITOR_V] AS SELECT PRS_PROCESS_ID, PRS_MODELL_ID, PRS_START_TIME, PRS_END_TIME, PRS_STATE, PRS_BUSINESS_KEY, PRS_SCENARIO_ID, PRS_ROOT_TOKEN, PRS_PROCESS_MODEL, PRS_VERSION_TAG, PRS_CREATE_TIME, PRS_NODE,datediff(ss,PRS_START_TIME,PRS_END_TIME) AS 'PRS_DURATION' FROM ORC_PROCESS_STATE
GO

CREATE VIEW [ORC_LTA_PROC_STATE_MONITOR_V] AS select PRS_PROCESS_ID,PRS_MODELL_ID,PRS_START_TIME,PRS_END_TIME,PRS_STATE,PRS_BUSINESS_KEY,PRS_SCENARIO_ID,PRS_ROOT_TOKEN,PRS_PROCESS_MODEL,PRS_VERSION_TAG, PRS_CREATE_TIME,datediff(ss,PRS_START_TIME,PRS_END_TIME) AS 'PRS_DURATION',PRS_BUSEVENT_TYPE,PRS_BUSEVENT_REFERENCE,PRS_BUSEVENT_ALIAS,PRS_ARCHIVE_DATE from ORC_LTA_PROCESS_STATE
GO

-- Changeset /opt/liquibase/data/orchestra_master_4.5.0.0.xml::change-4.5.0.0-12::akn::(Checksum: 6:9f57027e0e76a7762e8bf372e1242a0c)
INSERT INTO [ORC_SEC_ROLE_V2] ([OSR_SCENARIO], [OSR_IDENTIFIER], [OSR_DESC]) VALUES ('RUNTIME', 'RUNTIME:Scenario.SuspendResume', 'Suspend or Resume scenario triggers')
GO

INSERT INTO [ORC_SEC_USER_ROLES_V2] ([OUR_USER_ID], [OUR_ROLE_ID]) VALUES ('RUNTIME:admin', 'Scenario.SuspendResume')
GO

