-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.5.4.0.xml
-- Ran at: 09.02.15 10:05
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.5.4.0.xml::change-4.5.4.0-01::akn::(Checksum: 6:9ec3faeb7202663f9f36e2558aab22e6)
ALTER TABLE [ORC_WORK_QUEUE] DROP CONSTRAINT [PK_WORK_QUEUE_ID]
GO

ALTER TABLE [ORC_WORK_QUEUE] ALTER COLUMN [ID] VARCHAR(40)
GO

UPDATE [ORC_WORK_QUEUE] SET [ID] = 'dummy' WHERE [ID] IS NULL
GO

ALTER TABLE [ORC_WORK_QUEUE] ALTER COLUMN [ID] VARCHAR(40) NOT NULL
GO

ALTER TABLE [ORC_WORK_QUEUE] ADD CONSTRAINT [PK_WORK_QUEUE_ID] PRIMARY KEY ([ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_4.5.4.0.xml::change-4.5.4.0-02::akn::(Checksum: 6:fb0dd90ab0f4601006351c46cbc8237b)
DROP INDEX [ORC_TOPIC_QUEUE].IDX_ORC_TOPIC_QUEUE_ID_QUEUE_TYPE
GO

DROP INDEX [ORC_TOPIC_QUEUE].IDX_ORC_TOPIC_QUEUE_ID
GO

ALTER TABLE [ORC_TOPIC_QUEUE] ALTER COLUMN [ID] VARCHAR(40)
GO

UPDATE [ORC_TOPIC_QUEUE] SET [ID] = 'dummy' WHERE [ID] IS NULL
GO

ALTER TABLE [ORC_TOPIC_QUEUE] ALTER COLUMN [ID] VARCHAR(40) NOT NULL
GO

ALTER TABLE [ORC_TOPIC_QUEUE] ADD CONSTRAINT [PK_TOPIC_QUEUE_ID] PRIMARY KEY ([ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

DROP INDEX [ORC_TOPIC_QUEUE].IDX_ORC_TOPIC_QUEUE_TOPIC_ID
GO

CREATE NONCLUSTERED INDEX [IDX_ORC_TOPIC_QUEUE_TOPIC_ID] ON [ORC_TOPIC_QUEUE] ( [ORC_TOPIC_ID] ASC, [QUEUE_TYPE] ASC )
		     INCLUDE ( [STATE], [TARGET_NODE]) WITH (ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY]
GO

-- Changeset /opt/liquibase/data/orchestra_4.5.4.0.xml::change-4.5.4.0-03::akn::(Checksum: 6:12be5267213d8edea710965013701e6b)
CREATE NONCLUSTERED INDEX [IDX_PROC_FIFO_CACHE_PREF] ON [ORC_PROCESS_FIFO_SCHED_CACHE] ( [PFC_PROCESS_REFERENCE] ASC )
             INCLUDE ( [PFC_TARGET_NODE]) WITH (ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY]
GO

-- Changeset /opt/liquibase/data/orchestra_4.5.4.0.xml::change-4.5.4.0-04::akn::(Checksum: 6:c3d481b5bd942bbd6be474aa0abad468)
ALTER TABLE [ORC_SERVER_SETTINGS] ADD [MASS_OPERATION_BLOCK_SIZE] INT CONSTRAINT DF_ORC_SERVER_SETTINGS_MASS_OPERATION_BLOCK_SIZE DEFAULT '500'
GO

UPDATE [ORC_SERVER_SETTINGS] SET [MASS_OPERATION_BLOCK_SIZE] = 500
GO

