-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.5.6.0.xml
-- Ran at: 11/27/15 1:20 PM
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.5.6.0.xml::change-4.5.6.0-1::akn::(Checksum: 6:3a942c9ffce8da230df053e827a64f99)
CREATE TABLE [ORC_REST_SVC_CLIENT] ([RSC_SCENARIO] VARCHAR(250), [RSC_NAME] VARCHAR(250), [RSC_DATA] VARBINARY(MAX), [RSC_DEPLOYED_AT] datetime, [RSC_UNIQUE_NAME] VARCHAR(250) NOT NULL, CONSTRAINT [PK_ORC_SVC_CLIENT] PRIMARY KEY ([RSC_UNIQUE_NAME]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF))
GO

ALTER TABLE [ORC_REST_SVC_CLIENT] SET (LOCK_ESCALATION = TABLE)
GO

CREATE INDEX IDX_ORC_RSVC_SCENARIO ON [ORC_REST_SVC_CLIENT]([RSC_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_4.5.6.0.xml::change-4.5.6.0-2::akn::(Checksum: 6:6a0f0aa5d6ddc859dceb92c7b2f7e3be)
CREATE INDEX IDX_ORC_PROCESS_MODELLS_SCEN ON [ORC_PROCESS_MODELLS]([PMO_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_CHANNEL_SCEN ON [ORC_CHANNEL]([CHA_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_CONTENT_MAPPING_SCEN ON [ORC_CONTENT_MAPPING]([CMA_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_MESSAGE_MAPPING_SCEN ON [ORC_MESSAGE_MAPPING]([MMA_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_CONTENT_TYPE_SCEN ON [ORC_CONTENT_TYPE]([CTY_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_XML_SCHEMA_SCEN ON [ORC_XML_SCHEMA]([XSC_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_MESSAGE_INTERFACE_SCEN ON [ORC_MESSAGE_INTERFACE]([MIN_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_LANDSCAPE_SCEN ON [ORC_LANDSCAPE]([LAN_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_ARCHIVE_SCEN ON [ORC_ARCHIVE]([ARC_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_JAVA_CLASS_SCEN ON [ORC_JAVA_CLASS]([JCL_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_SVC_PROVIDER_SCEN ON [ORC_SVC_PROVIDER]([SPR_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_PRT_PARTNERCONFIG_SCEN ON [ORC_PRT_PARTNERCONFIG]([PRT_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_LOOKUPTABLE_SCEN ON [ORC_LOOKUPTABLE]([LUT_SCENARIO]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

