-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.7.0.0.xml
-- Ran at: 7/5/17 12:55 PM
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-1::akn::(Checksum: 6:0b3d233300c07781ba3aa99d28bc503f)
ALTER TABLE [ORC_EVENT_PROCESS_TOKEN] ALTER COLUMN [EVT_ORCHESTRA_LINK] VARCHAR(300)
GO

ALTER TABLE [ORC_WORKLIST_TYPE] ADD [WLT_LABEL] VARCHAR(20)
GO

ALTER TABLE [ORC_EVENT_PROCESS_TOKEN] ADD [EVT_VARLOG] VARBINARY(MAX)
GO

ALTER TABLE [ORC_EVENT_PROCESS_TOKEN] ADD [EVT_USE_VARLOG] INT
GO

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-2_Syslog::akn::(Checksum: 6:4d3a527fff1a9cff37c7415b0532f8da)
CREATE TABLE [ORC_SYSLOG_QUEUE] ([ITEMTYPE] VARCHAR(256) NOT NULL, [DISCRIMINATOR] VARCHAR(256) NOT NULL, [CREATEDAT] datetime CONSTRAINT DF_ORC_SYSLOG_QUEUE_CREATEDAT DEFAULT GETDATE() NOT NULL, [WORKOBJECT] VARBINARY(MAX), [ID] VARCHAR(50) NOT NULL, [ACTION] CHAR(1) CONSTRAINT DF_ORC_SYSLOG_QUEUE_ACTION DEFAULT 'W', [NAME] VARCHAR(256), [STATE] INT, [TARGET_NODE] VARCHAR(255), [NODE_TICK] VARCHAR(255), [QUEUE_TYPE] VARCHAR(1), [PRIORITY] INT, [ORC_TOPIC_OWNER] VARCHAR(256), [ORC_TOPIC_ID] VARCHAR(256), [NEXT_SCHEDULE_TIME] datetime, [DELETETOKEN] INT)
GO

ALTER TABLE [ORC_SYSLOG_QUEUE] SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE [ORC_SYSLOG_QUEUE] ADD CONSTRAINT [PK_SYSLOG_ID] PRIMARY KEY ([ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_TOPIC_ID ON [ORC_SYSLOG_QUEUE]([ORC_TOPIC_ID], [QUEUE_TYPE], [STATE]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_TOPIC_OWNER ON [ORC_SYSLOG_QUEUE]([ORC_TOPIC_OWNER], [QUEUE_TYPE], [STATE]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_STATE_TYPE_ID ON [ORC_SYSLOG_QUEUE]([STATE], [QUEUE_TYPE], [ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_S_T_Q_N ON [ORC_SYSLOG_QUEUE]([STATE], [ORC_TOPIC_ID], [TARGET_NODE], [QUEUE_TYPE], [NEXT_SCHEDULE_TIME]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE UNIQUE INDEX IDX_SYSLOG_QUEUE_STAT_TYP_PRIO ON [ORC_SYSLOG_QUEUE]([STATE], [QUEUE_TYPE], [PRIORITY], [ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE TABLE [ORC_SYSLOG_QUEUE_DEL_TOPIC] ([DTO_TOPIC] VARCHAR(256) NOT NULL, [DTO_DELETETOKEN] INT NOT NULL, [DTO_GLOBAL] INT NOT NULL, [DTO_NODEID] VARCHAR(32) NOT NULL, [DTO_IDENT] INT NOT NULL, [DTO_QUEUE_TYPE] VARCHAR(1) NOT NULL)
GO

ALTER TABLE [ORC_SYSLOG_QUEUE_DEL_TOPIC] SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE [ORC_SYSLOG_QUEUE_DEL_TOPIC] ADD CONSTRAINT [PK_SYSLOG_IDENT] PRIMARY KEY ([DTO_IDENT]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE UNIQUE INDEX IDX_ORC_SQ_DELTOPIC_LOOKUP ON [ORC_SYSLOG_QUEUE_DEL_TOPIC]([DTO_NODEID], [DTO_QUEUE_TYPE], [DTO_GLOBAL], [DTO_TOPIC], [DTO_DELETETOKEN]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-3_LTA::akn::(Checksum: 6:d6f9ac2f7f060a7db618c17812715c73)
CREATE TABLE [ORC_LTA_MESSAGE_DATA] ([MES_MESSAGE_ID] VARCHAR(255) NOT NULL, [MES_ARCHIVE_TIME] datetime NOT NULL, [MES_PROPS] VARBINARY(MAX) NOT NULL, [MES_CONTENT] VARBINARY(MAX))
GO

ALTER TABLE [ORC_LTA_MESSAGE_DATA] SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE [ORC_LTA_MESSAGE_DATA] ADD CONSTRAINT [PK_LTA_MSGDATA_ID] PRIMARY KEY ([MES_MESSAGE_ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE TABLE [ORC_LTA_MESSAGE_PAGE] ([MPA_MESSAGE_ID] VARCHAR(255) NOT NULL, [MPA_ID] INT NOT NULL, [MPA_PAGE_TYPE] INT NOT NULL, [MPA_ARCHIVE_TIME] datetime NOT NULL, [MPA_DATA] VARBINARY(MAX) NOT NULL)
GO

ALTER TABLE [ORC_LTA_MESSAGE_PAGE] SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE [ORC_LTA_MESSAGE_PAGE] ADD CONSTRAINT [PK_LTA_MSG_PAGE] PRIMARY KEY ([MPA_MESSAGE_ID], [MPA_ID], [MPA_PAGE_TYPE]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE TABLE [ORC_LTA_PROCESS_DATA] ([PRS_PROCESS_ID] VARCHAR(255) NOT NULL, [PRS_ARCHIVE_DATE] datetime NOT NULL, [PRS_PROCESS_DATA] VARBINARY(MAX) NOT NULL)
GO

ALTER TABLE [ORC_LTA_PROCESS_DATA] SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE [ORC_LTA_PROCESS_DATA] ADD CONSTRAINT [PK_LTA_PRODATA_ID] PRIMARY KEY ([PRS_PROCESS_ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE TABLE [ORC_LTA_MESSAGE_LIST_DATA] ([MLI_IDENTIFIER] VARCHAR(255) NOT NULL, [MLI_ARCHIVE_TIME] datetime NOT NULL, [MLI_DATA] VARBINARY(MAX) NOT NULL)
GO

ALTER TABLE [ORC_LTA_MESSAGE_LIST_DATA] SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE [ORC_LTA_MESSAGE_LIST_DATA] ADD CONSTRAINT [PK_LTA_MSGLIST_ID] PRIMARY KEY ([MLI_IDENTIFIER]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-5_Index::akn::(Checksum: 6:ab1249e973e27a3b18511690c8f7c494)
ALTER TABLE [ORC_MESSAGE_LIST_ENTRY_PROP] DROP CONSTRAINT [PK_MLP_ID_KEY_REF]
GO

ALTER TABLE [ORC_MESSAGE_LIST_ENTRY_PROP] ADD CONSTRAINT [PK_MLP_ID_KEY_REF] PRIMARY KEY ([MLP_ID], [MLP_REFERENCE], [MLP_KEY]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_CLUST_LOCK_STAT ON [ORC_CLUSTER_LOCK_STATE]([ORC_LOCK_SCENARIO], [ORC_LOCK_NAME], [ORC_LOCK_OWNER]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_ORC_EVENT_SOURCE ON [ORC_EVENT_SYSTEM]([EVT_SOURCE], [EVT_DESCRIPTION]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

DROP INDEX [ORC_MESSAGE].IDX_ORC_MESSAGE_CREATED_AT
GO

CREATE INDEX IDX_ORC_MESSAGE_CREATED_AT ON [ORC_MESSAGE]([MES_TOUCHED], [MES_CREATED_AT]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX IDX_TRANSACTION_STATE ON [ORC_TRANSACTION]([TRA_STATE]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

DROP INDEX [ORC_MESSAGE_LIST].IDX_ORC_MESSAGE_LIST_LEASETIME
GO

CREATE INDEX IDX_ORC_MESSAGE_LIST_LEASETIME ON [ORC_MESSAGE_LIST]([MLI_TYPE], [MLI_TOUCHED], [MLI_LEASE_TIME]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-6::akn::(Checksum: 6:4fc337a0e6129e84b34838a0cc17c014)

IF EXISTS ( SELECT 'X' FROM sys.indexes WHERE object_id = OBJECT_ID('ORC_TOPIC_QUEUE') AND name='IDX_ORC_TOPIC_QUEUE_TOPIC_ID')
	DROP INDEX [ORC_TOPIC_QUEUE].IDX_ORC_TOPIC_QUEUE_TOPIC_ID
ELSE
	DROP INDEX [ORC_TOPIC_QUEUE].IDX_TOPIC_QUEUE_TOPIC_ID
GO

CREATE NONCLUSTERED INDEX [IDX_TOPIC_QUEUE_TOPIC_ID] ON [ORC_TOPIC_QUEUE] ([ORC_TOPIC_ID], [QUEUE_TYPE], [STATE], [TARGET_NODE], [ID])
			 INCLUDE ([DELETETOKEN], [WORKOBJECT], [DISCRIMINATOR], [ORC_TOPIC_OWNER]) WITH (ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_4.7.0.0.xml::change-4.7.0.0-7_Index::akn::(Checksum: 6:ce7f525b9cabff9bc0d94b1ebbb4982e)
UPDATE [ORC_ESB_SIGNAL_STATE] SET [EST_IDENTIFIER] = 'dummy' WHERE [EST_IDENTIFIER] IS NULL
GO

ALTER TABLE [ORC_ESB_SIGNAL_STATE] ALTER COLUMN [EST_IDENTIFIER] VARCHAR(64) NOT NULL
GO

ALTER TABLE [ORC_ESB_SIGNAL_STATE] ADD CONSTRAINT [PK_ORC_ESB_SIGSTA] PRIMARY KEY ([EST_IDENTIFIER]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

