
CREATE TABLE ORC_MESSAGE_LIST
(
  MLI_IS_SYSTEM   NUMBER(1),
  MLI_AREA        VARCHAR2(256 BYTE),
  MLI_IDENTIFIER  VARCHAR2(256 BYTE),
  MLI_ID          NUMBER(18)
);

CREATE TABLE ORC_MESSAGE_LIST_ENTRY
(
  MLE_INDEX        NUMBER(10),
  MLE_MESSAGE_REF  VARCHAR2(256 BYTE),
  MLE_ID           NUMBER(18)
);

CREATE TABLE ORC_MESSAGE_LIST_ENTRY_PROP
(
  MLP_INDEX  NUMBER(10),
  MLP_KEY    VARCHAR2(256 BYTE),
  MLP_VALUE  VARCHAR2(512 BYTE),
  MLP_ID     NUMBER(18)
);

insert into ORC_SEQUENCE_COUNTER(SCO_CATEGORY, SCO_COUNTER) values ('MESSAGELIST', 9);
COMMIT;

CREATE TABLE ORC_SVC_DECLARATION
(
  SDC_SCENARIO     VARCHAR2(250),
  SDC_NAME         VARCHAR2(250),
  SDC_DATA         BLOB,
  SDC_DEPLOYED_AT  DATE,
  SDC_UNIQUE_NAME  VARCHAR2(250)
);

CREATE TABLE ORC_SVC_PROVIDER
(
  SPR_SCENARIO     VARCHAR2(250),
  SPR_NAME         VARCHAR2(250),
  SPR_DATA         BLOB,
  SPR_DEPLOYED_AT  DATE,
  SPR_UNIQUE_NAME  VARCHAR2(250)
);

















create table ORC_SEC_USER_PKCS12
(
	OUS_USER_ID 		varchar2(255) not null, 
	OUS_SCENARIO 		varchar2(255), 
	OUS_KEYPASSWORD 	varchar2(255), 
	OUS_STOREPASSWORD 	varchar2(255), 
	OUS_PKCS12STORE 	blob, 
	primary key (OUS_USER_ID)
);

create table ORC_SEC_USER_SSH
(
	OUS_USER_ID 		varchar2(255) not null, 
	OUS_SCENARIO 		varchar2(255), 
	OUS_PASSWORD 		varchar2(255), 
	OUS_CERTIFICATE 	blob, 
	primary key (OUS_USER_ID)
);

CREATE TABLE ORC_PRT_PARTNERCONFIG
(
	PRT_SCENARIO     	VARCHAR2(250),
	PRT_NAME         	VARCHAR2(250),
	PRT_DATA         	BLOB,
	PRT_DEPLOYED_AT  	DATE,
	PRT_UNIQUE_NAME  	VARCHAR2(250)
);

Insert into ORC_CLUSTER_LOCK (ORC_LOCK_NAME, ORC_LOCK_STATE, ORC_LOCK_OWNER, ORC_LOCK_SCENARIO) Values  ('MESSAGELIST', NULL, NULL, 'GLOBAL');

ALTER TABLE orc_recovery_data MODIFY  RDA_TOKEN_ID varchar2(250);

COMMIT;
