--- Update Script Oracle SQL für V4.3.3.15 ----
ALTER TABLE ORC_PROCESS_ARBORT
  RENAME COLUMN PRA_CHILD_PROCESS TO PRA_PROCESSINSTANCE;

ALTER TABLE ORC_PROCESS_ARBORT
  ADD PRA_PROCSSMODELL VARCHAR(255);

CREATE VIEW ORC_PROCESS_STATE_BUSINESS_KEY
    AS SELECT * FROM
         ORC_PROCESS_STATE,
         ORC_PROCESS_EXT_BUSINESS_KEYS
    WHERE PEK_PROCESS_ID = PRS_PROCESS_ID;
    
CREATE INDEX IDX_ORC_PROCESS_STATE_1 ON ORC_PROCESS_STATE(PRS_SCENARIO_ID,PRS_STATE);

CREATE INDEX IDX_ORC_PROCESS_STATE_2 ON ORC_PROCESS_STATE(PRS_SCENARIO_ID,PRS_MODELL_ID);

CREATE INDEX IDX_ORC_PROCESS_EXT_BK ON ORC_PROCESS_EXT_BUSINESS_KEYS(PEK_BUSINESS_KEY_NAME,PEK_BUSINESS_KEY);
