alter table ORC_PROCESS_RUNTIME_STATE drop primary key;

drop index IDX_ORC_PR_RT_STATE;
  
drop index IDX_ORC_PR_FP_MODEL;

alter table ORC_PROCESS_RUNTIME_STATE modify (PRS_PROCESS not null);

alter table ORC_PROCESS_RUNTIME_STATE add constraint PK_ORC_PR_RT_STATE primary key (PRS_PROCESS);

CREATE INDEX IDX_ORC_PR_FP_MODEL ON ORC_PROCESS_RUNTIME_STATE(PRS_PROCESSMODELL, PRS_STATE, PRS_NODE_ID);
