-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.5.1.0.xml
-- Ran at: 31.07.14 15:21
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-01::akn::(Checksum: 6:b4b1438959cdfa538f2ecc0d852116c8)
ALTER TABLE ORC_PROCESS_FIFO_SCHEDULE MODIFY PFS_ID VARCHAR2(50);

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-02::akn::(Checksum: 6:6f0693225b07d78edc17111d23bfa338)
ALTER TABLE ORC_ALERT_DATA ADD NODE_ID VARCHAR2(255) DEFAULT 'ORC' NOT NULL;

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-03::akn::(Checksum: 6:aa2305f31af5c51bdb6580be28aa841d)
DROP INDEX IDX_SEQ_COUNTER_CATEGORY;

UPDATE ORC_SEQUENCE_COUNTER SET SCO_CATEGORY = 'ORC' WHERE SCO_CATEGORY IS NULL;

ALTER TABLE ORC_SEQUENCE_COUNTER MODIFY SCO_CATEGORY NOT NULL;

ALTER TABLE ORC_SEQUENCE_COUNTER ADD CONSTRAINT PK_SEQ_COUNTER_CATEGORY PRIMARY KEY (SCO_CATEGORY);

DROP INDEX IDX_MSG_DATA_MSG_ID;

ALTER TABLE ORC_MESSAGE_DATA ADD CONSTRAINT PK_MSG_DATA_MSG_ID PRIMARY KEY (MSD_MSG_ID);

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-04::akn::(Checksum: 6:706e1b31fb477bed8328e25a8d68791d)
CREATE TABLE ORC_COMMIT_DESC (OCD_TAID VARCHAR2(255) NOT NULL, OCD_TIME TIMESTAMP, OCD_NODE VARCHAR2(255) NOT NULL);

ALTER TABLE ORC_COMMIT_DESC ADD CONSTRAINT PK_COMDE_TAID_NODE PRIMARY KEY (OCD_TAID, OCD_NODE);

ALTER TABLE ORC_WORK_QUEUE ADD NEXT_SCHEDULE_TIME TIMESTAMP;

CREATE INDEX IDX_WORK_QUEUE_S_T_Q_N ON ORC_WORK_QUEUE(STATE, TARGET_NODE, QUEUE_TYPE, NEXT_SCHEDULE_TIME);

ALTER TABLE ORC_TOPIC_QUEUE ADD NEXT_SCHEDULE_TIME TIMESTAMP;

CREATE INDEX IDX_TOPIC_QUEUE_S_T_Q_N ON ORC_TOPIC_QUEUE(STATE, TARGET_NODE, QUEUE_TYPE, NEXT_SCHEDULE_TIME);

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.4.3.2-02::akn::(Checksum: 6:2a766a9e610e3f13dfb7cdeb2ac61cab)
ALTER TABLE ORC_KPI_INSTANCE ADD CONSTRAINT PK_ORC_KPI_INSTANCE PRIMARY KEY (KIN_IDENTIFIER);

ALTER TABLE ORC_KPI_DIM_VALUE ADD CONSTRAINT PK_ORC_KPI_DIM_VALUE PRIMARY KEY (KDV_INSTANCEID, KDV_NAME);

ALTER TABLE ORC_KPI_VALUE ADD CONSTRAINT PK_ORC_KPI_VALUE PRIMARY KEY (KVA_INSTANCEID, KVA_TIMEINDEX);

COMMIT;

