
create table ORC_SEQUENCE_COUNTER
(
	SCO_CATEGORY	varchar(32),
	SCO_COUNTER		integer
)ENGINE= innodb;

CREATE TABLE ORC_PROCESS_FIFO_SCHEDULE
(
  PFS_ID                 VARCHAR(30)      NOT NULL,
  PFS_SCENARIO           VARCHAR(256)     NOT NULL,
  PFS_MODELL_REFERENCE   VARCHAR(256)     NOT NULL,
  PFS_PROCESS_REFERENCE  VARCHAR(256)     NOT NULL,
  PFS_TOKEN_REFERENCE    VARCHAR(256)     NOT NULL,
  PFS_VARIABLES          BLOB,
  PFS_TARGET_NODE        VARCHAR(256),
  PFS_STATE              VARCHAR(10)      NOT NULL
)ENGINE= innodb;

insert into ORC_SEQUENCE_COUNTER( SCO_CATEGORY, SCO_COUNTER) values ( 'FIFO.QUEUE', 0 );
commit;

alter table ORC_WORK_QUEUE add QUEUE_TYPE varchar(1);

alter table ORC_BUSINESS_TRANSACTION add OBT_APPLICATION_STATE varchar(30);

commit;

