
ALTER TABLE ORC_PROCESS_RUNTIME_STATE DROP PRIMARY KEY;

DROP INDEX IDX_ORC_PR_FP_MODEL ON ORC_PROCESS_RUNTIME_STATE;

ALTER TABLE ORC_PROCESS_RUNTIME_STATE MODIFY PRS_PROCESS varchar(255) NOT NULL;

ALTER TABLE ORC_PROCESS_RUNTIME_STATE add constraint PK_ORC_PR_RT_STATE PRIMARY KEY (PRS_PROCESS);

CREATE INDEX IDX_ORC_PR_FP_MODEL ON ORC_PROCESS_RUNTIME_STATE(PRS_PROCESSMODELL, PRS_STATE, PRS_NODE_ID);

commit;
