/* MySQL Script 47 V4.3.4.18 */

ALTER TABLE ORC_MESSAGE modify MES_CREATED_AT TIMESTAMP NULL;

ALTER TABLE ORC_MESSAGE_LIST modify MLI_CREATED_AT TIMESTAMP NULL;

ALTER TABLE ORC_PROCESS_SCENARIO modify PSC_DEPLOYED_AT TIMESTAMP NULL;

ALTER TABLE ORC_PROCESS_STATE modify PRS_START_TIME TIMESTAMP NULL;

ALTER TABLE ORC_PROCESS_EXECUTION modify ORC_FIRST_RUN TIMESTAMP NULL;

ALTER TABLE ORC_PROCESS_MODELLS modify PMO_DEPLOYED_AT TIMESTAMP NULL;

