ALTER TABLE ORC_MONITOR_SETTINGS ADD (
  ORC_MESSAGEPANEL_ACTIVE  integer,
  ORC_MESSAGEPANEL_TRESHOLD  integer,
  ORC_MESSAGEPANEL_VISIBLETIME   integer,
  ORC_THEME  VARCHAR(255)
);

ALTER TABLE ORC_MONITOR_SETTINGS DROP COLUMN ORC_LOGOFF_PERIODE;

update ORC_MONITOR_SETTINGS set ORC_MESSAGEPANEL_ACTIVE = 1
 where ORC_MESSAGEPANEL_ACTIVE is null;

update ORC_MONITOR_SETTINGS set ORC_MESSAGEPANEL_TRESHOLD = 10
 where ORC_MESSAGEPANEL_TRESHOLD is null;

update ORC_MONITOR_SETTINGS set ORC_MESSAGEPANEL_VISIBLETIME = 10000
 where ORC_MESSAGEPANEL_VISIBLETIME is null;
 
update ORC_MONITOR_SETTINGS set ORC_THEME = 'standard'
 where ORC_THEME is null;

commit;

CREATE TABLE ORC_PROCESS_EXECUTION
(
  ORC_PROCESS_MODEL           VARCHAR(255) NOT NULL,
  ORC_SCENARIO_ID             VARCHAR(255),
  ORC_TOTAL_PROCESS_COUNT     bigint,
  ORC_TOTAL_PROCESS_DURATION  bigint,
  ORC_FIRST_RUN               TIMESTAMP NULL,
  ORC_LAST_RUN                TIMESTAMP NULL,
  ORC_MIN_DURATION  bigint,
  ORC_MAX_DURATION  bigint
);

CREATE TABLE ORC_SERVER_SETTINGS
(
  ID              VARCHAR(255),
  LOGOUT_PERIODE  integer,
  LOGLEVEL        VARCHAR(255)
);

ALTER TABLE ORC_PROCESS_EXECUTION ADD CONSTRAINT PK_ORC_PROCESS_EXECUTION PRIMARY KEY (ORC_PROCESS_MODEL);





ALTER TABLE ORC_SERVER_SETTINGS ADD CONSTRAINT PK_ORC_SERVER_SETTINGS PRIMARY KEY (ID);

ALTER TABLE ORC_MONITOR_SETTINGS ADD CONSTRAINT PK_ORC_MONITOR_SETTINGS PRIMARY KEY (ORC_USERID);

ALTER TABLE ORC_MONITOR_TABLESETTINGS ADD CONSTRAINT PK_ORC_MONITOR_TABLESETTINGS PRIMARY KEY (ORC_PARENT_USERID,ORC_TABLECLASS);

INSERT INTO ORC_SEC_ROLE_V2(OSR_SCENARIO, OSR_IDENTIFIER, OSR_DESC) VALUES ('RUNTIME', 'RUNTIME:ServerAdministrator', NULL);
INSERT INTO ORC_SEC_ROLE_V2(OSR_SCENARIO, OSR_IDENTIFIER, OSR_DESC) VALUES ('RUNTIME', 'RUNTIME:Remote.Administrator', NULL);

INSERT INTO ORC_SEC_USER_ROLES_V2(OUR_USER_ID, OUR_ROLE_ID) VALUES ('RUNTIME:admin', 'ServerAdministrator');



commit;

alter table ORC_WORK_QUEUE add(PRIORITY integer default 0 not null);
