/* MySQL - Script 45 (V4.3.4.11) */

CREATE TABLE ORC_PROCESS_OVERVIEW (
  POV_SCENARIO VARCHAR(255) NOT NULL,
  POV_RUNNING BIGINT NOT NULL,
  POV_PAUSED BIGINT NOT NULL,
  POV_ABORTED BIGINT NOT NULL,
  POV_FINISHED BIGINT NOT NULL,
  POV_WARNING BIGINT NOT NULL
);

ALTER TABLE ORC_PROCESS_OVERVIEW
 ADD CONSTRAINT PK_ORC_PROCESS_OVERVIEW
 PRIMARY KEY(POV_SCENARIO);
 
/* Change Index from Script 40 */

ALTER TABLE ORC_PROCESSINSTANCE_STATE DROP INDEX IDX_ORC_PROCESINST_STATE_ID;

ALTER TABLE ORC_PROCESSINSTANCE_STATE ADD CONSTRAINT PK_PROCESSINSTANCE_STATE PRIMARY KEY (PRS_ID);

COMMIT;
