CREATE BUFFERPOOL "USERPOOL16KB"
  IMMEDIATE
  ALL DBPARTITIONNUMS
  SIZE AUTOMATIC
  NUMBLOCKPAGES 0
  PAGESIZE 16K;

CREATE BUFFERPOOL "USERPOOL32KB"
  IMMEDIATE
  ALL DBPARTITIONNUMS
  SIZE AUTOMATIC
  NUMBLOCKPAGES 0
  PAGESIZE 32K;

CREATE BUFFERPOOL "STEMPORARY16KB"
  IMMEDIATE
  ALL DBPARTITIONNUMS
  SIZE AUTOMATIC
  NUMBLOCKPAGES 0
  PAGESIZE 16K;

CREATE BUFFERPOOL "STEMPORARY32KB"
  IMMEDIATE
  ALL DBPARTITIONNUMS
  SIZE AUTOMATIC
  NUMBLOCKPAGES 0
  PAGESIZE 32K;

CREATE BUFFERPOOL "USERTEMPORARY16KB"
  IMMEDIATE
  ALL DBPARTITIONNUMS
  SIZE AUTOMATIC
  NUMBLOCKPAGES 0
  PAGESIZE 16K;

CREATE BUFFERPOOL "USERTEMPORARY32KB"
  IMMEDIATE
  ALL DBPARTITIONNUMS
  SIZE AUTOMATIC
  NUMBLOCKPAGES 0
  PAGESIZE 32K;

CREATE REGULAR TABLESPACE "USERPOOL16KB"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  MANAGED BY SYSTEM
  USING ( 'C:\DB2\NODE0000\SQL00002\USERPOOLCONTAINER' )
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "USERPOOL16KB"
  OVERHEAD 7.5
  TRANSFERRATE 0.06
  NO FILE SYSTEM CACHING
  DROPPED TABLE RECOVERY ON;

CREATE REGULAR TABLESPACE "USERPOLL32KB"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 32K
  MANAGED BY SYSTEM
  USING ( 'C:\DB2\NODE0000\SQL00002\USERPOOL32KB' )
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "USERPOOL32KB"
  OVERHEAD 7.5
  TRANSFERRATE 0.06
  NO FILE SYSTEM CACHING
  DROPPED TABLE RECOVERY ON;

CREATE SYSTEM TEMPORARY TABLESPACE "STEMP16KB"
  IN DATABASE PARTITION GROUP "IBMTEMPGROUP"
  PAGESIZE 16K
  MANAGED BY SYSTEM
  USING ( 'C:\DB2\NODE0000\SQL00002\STEMP16KB' )
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "STEMPORARY16KB"
  OVERHEAD 7.5
  TRANSFERRATE 0.06
  NO FILE SYSTEM CACHING;

CREATE SYSTEM TEMPORARY TABLESPACE "STEMP32KB"
  IN DATABASE PARTITION GROUP "IBMTEMPGROUP"
  PAGESIZE 32K
  MANAGED BY SYSTEM
  USING ( 'C:\DB2\NODE0000\SQL00002\STEMP32KB' )
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "STEMPORARY32KB"
  OVERHEAD 7.5
  TRANSFERRATE 0.06
  NO FILE SYSTEM CACHING;

CREATE USER TEMPORARY TABLESPACE "USERTEMP16KB"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 16K
  MANAGED BY SYSTEM
  USING ( 'C:\DB2\NODE0000\SQL00002\USERTEMP16KB' )
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "USERTEMPORARY16KB"
  OVERHEAD 7.5
  TRANSFERRATE 0.06
  NO FILE SYSTEM CACHING;

CREATE USER TEMPORARY TABLESPACE "USERTEMP32KB"
  IN DATABASE PARTITION GROUP "IBMDEFAULTGROUP"
  PAGESIZE 32K
  MANAGED BY SYSTEM
  USING ( 'C:\DB2\NODE0000\SQL00002\USERTEMP32KB' )
  EXTENTSIZE 32
  PREFETCHSIZE 32
  BUFFERPOOL "USERTEMPORARY32KB"
  OVERHEAD 7.5
  TRANSFERRATE 0.06
  NO FILE SYSTEM CACHING;

COMMIT;