ALTER TABLE ORC_WORK_QUEUE CHANGE WORKOBJECT WORKOBJECT BLOB;

CREATE TABLE ORC_DEL_PROCESS
(
  DPR_PROCESS_ID   bigint,
  DPR_SCENARIO_ID  VARCHAR(100),
  DPR_REFERENCE    VARCHAR(100)
);

CREATE INDEX IDX_DEL_PROCESS_ID ON ORC_DEL_PROCESS
(DPR_PROCESS_ID);

CREATE INDEX IDX_MSG_REFERRER_MESSAGE_ID ON ORC_MESSAGE_REFERERS(MRE_MESSAGE_ID);

ALTER TABLE JBPM_BYTEARRAY
ADD PROCESSINSTANCE_EXT bigint;

CREATE INDEX IDX_BYTEARRAY_PROCINST_EXT ON JBPM_BYTEARRAY(PROCESSINSTANCE_EXT);

CREATE INDEX IDX_MSG_DATA_MSG_ID ON ORC_MESSAGE_DATA(MSD_MSG_ID);


ALTER TABLE ORC_EVT_LOCAL_VARIABLES CHANGE EVV_VALUE EVV_VALUE VARCHAR(512);

ALTER TABLE ORC_EVT_PROCESS_VARIABLES CHANGE EVV_VALUE EVV_VALUE VARCHAR(512);


CREATE TABLE ORC_PROCESS_ARBORT
(
  PRA_PARENT_PROCESS  VARCHAR(255),
  PRA_CHILD_PROCESS   VARCHAR(255),
  PRA_PARENT_TOKEN    VARCHAR(255)
);


CREATE INDEX IDX_ORC_PROC_ABORT_CHILD_PROC ON ORC_PROCESS_ARBORT
(PRA_CHILD_PROCESS);


UPDATE JBPM_PROCESSINSTANCE SET ROOTTOKEN_ = NULL;

DELETE FROM JBPM_VARIABLEINSTANCE;

DELETE FROM JBPM_TOKENVARIABLEMAP;

DELETE FROM JBPM_MODULEINSTANCE;

DELETE FROM JBPM_BYTEBLOCK;

DELETE FROM JBPM_BYTEARRAY;

DELETE FROM JBPM_TOKEN;

DELETE FROM JBPM_PROCESSINSTANCE;

DELETE FROM JBPM_LOG;

COMMIT;