--  *********************************************************************
--  Create Database Script
--  *********************************************************************
--  Change Log: /opt/liquibase/data/orchestra_4.5.3.0.xml
--  Ran at: 08.12.14 17:04
--  Liquibase version: 2.0.5
--  *********************************************************************

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-01::akn::(Checksum: 6:0090e88c99824bbaff951b4d7602fa81)
UPDATE ORC_CLUSTER_ENVIRONMENT SET CEN_NODE_NAME = 'ORC' WHERE CEN_NODE_NAME IS NULL;

ALTER TABLE ORC_CLUSTER_ENVIRONMENT MODIFY CEN_NODE_NAME VARCHAR(255) NOT NULL;

ALTER TABLE ORC_CLUSTER_ENVIRONMENT ADD PRIMARY KEY (CEN_NODE_NAME);

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-02::akn::(Checksum: 6:42e7aad1ff0decb45f9e8885e7728412)
ALTER TABLE ORC_SEQUENCE_COUNTER DROP PRIMARY KEY;

ALTER TABLE ORC_SEQUENCE_COUNTER MODIFY SCO_CATEGORY VARCHAR(64);

UPDATE ORC_SEQUENCE_COUNTER SET SCO_CATEGORY = 'ORC' WHERE SCO_CATEGORY IS NULL;

ALTER TABLE ORC_SEQUENCE_COUNTER MODIFY SCO_CATEGORY VARCHAR(64) NOT NULL;

ALTER TABLE ORC_SEQUENCE_COUNTER ADD PRIMARY KEY (SCO_CATEGORY);

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-03::akn::(Checksum: 6:ab39234df3ed46e61f94f447df73cda7)
DROP INDEX IDX_ORC_WORK_QUEUE_2 ON ORC_WORK_QUEUE;

DROP INDEX IDX_PROCESS_FIFO_SCHEDULE_ID ON ORC_PROCESS_FIFO_SCHEDULE;

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-05::akn::(Checksum: 6:c882e87463c0e72fd74bd0609ef2af1b)
INSERT INTO ORC_CLUSTER_LOCK (ORC_LOCK_NAME, ORC_LOCK_SCENARIO) VALUES ('LTA', 'GLOBAL');

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-06::akn::(Checksum: 6:fe9ef52154db13164a7a9124e8499a83)
ALTER TABLE ORC_PROCESSINSTANCE_STATE ADD PRS_CLUSTER_LEASE VARCHAR(255);

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-08-1::akn::(Checksum: 6:ad9f5258588678596ec307d24cc690de)
ALTER TABLE ORC_PROCESS_FIFO_SCHED_CACHE DROP PRIMARY KEY;

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-08-2::akn::(Checksum: 6:f4b13793aec7aefd374ab5c27832d4f5)
ALTER TABLE ORC_PROCESS_FIFO_SCHED_CACHE ADD PRIMARY KEY (PFC_ID, PFC_MODELL_REFERENCE);

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-09::akn::(Checksum: 6:d5a4eca404b21fbbb510ff78fbf1e77b)
DROP INDEX IDX_PROCESS_FIFO_CACHE ON ORC_PROCESS_FIFO_SCHED_CACHE;

CREATE INDEX IDX_PROCESS_FIFO_CACHE ON ORC_PROCESS_FIFO_SCHED_CACHE(PFC_MODELL_REFERENCE, PFC_TARGET_NODE);

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-10::akn::(Checksum: 6:2c09d4c12f15a3008d85d5f8a136ee4c)
DROP INDEX IDX_ORC_MSG_LIST_ID ON ORC_MESSAGE_LIST;

UPDATE ORC_MESSAGE_LIST SET MLI_ID = '0' WHERE MLI_ID IS NULL;

ALTER TABLE ORC_MESSAGE_LIST MODIFY MLI_ID BIGINT NOT NULL;

ALTER TABLE ORC_MESSAGE_LIST ADD PRIMARY KEY (MLI_ID);

DROP INDEX IDX_ORC_MSG_LISTENT_ID_MSGREF ON ORC_MESSAGE_LIST_ENTRY;

DROP INDEX IDX_ORC_MSG_LISTENT_ID_REFER ON ORC_MESSAGE_LIST_ENTRY;

UPDATE ORC_MESSAGE_LIST_ENTRY SET MLE_ID = '0' WHERE MLE_ID IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY MODIFY MLE_ID BIGINT NOT NULL;

UPDATE ORC_MESSAGE_LIST_ENTRY SET MLE_REFERENCE = 'dummy' WHERE MLE_REFERENCE IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY MODIFY MLE_REFERENCE VARCHAR(256) NOT NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY ADD PRIMARY KEY (MLE_ID, MLE_REFERENCE);

DROP INDEX IDX_ORC_MSG_LISTPRP_ID_KEY_VAL ON ORC_MESSAGE_LIST_ENTRY_PROP;

DROP INDEX IDX_ORC_MSG_LISTPRP_ID_REF_KEY ON ORC_MESSAGE_LIST_ENTRY_PROP;

UPDATE ORC_MESSAGE_LIST_ENTRY_PROP SET MLP_ID = '0' WHERE MLP_ID IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP MODIFY MLP_ID BIGINT NOT NULL;

UPDATE ORC_MESSAGE_LIST_ENTRY_PROP SET MLP_KEY = 'dummy' WHERE MLP_KEY IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP MODIFY MLP_KEY VARCHAR(256) NOT NULL;

UPDATE ORC_MESSAGE_LIST_ENTRY_PROP SET MLP_REFERENCE = 'dummy' WHERE MLP_REFERENCE IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP MODIFY MLP_REFERENCE VARCHAR(256) NOT NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP ADD PRIMARY KEY (MLP_ID, MLP_KEY, MLP_REFERENCE);

CREATE INDEX IDX_ORC_MSG_LISTPRP_ID_KEY_VAL ON ORC_MESSAGE_LIST_ENTRY_PROP(MLP_ID, MLP_KEY, MLP_VALUE);

--  Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-11::akn::(Checksum: 6:ee5857d2d2fe76046d476652158f59c4)
DROP INDEX IDX_PROCESS_FIFO_SCHEDULE_MODEL_REF ON ORC_PROCESS_FIFO_SCHEDULE;

