--  *********************************************************************
--  Create Database Script
--  *********************************************************************
--  Change Log: /opt/liquibase/data/orchestra_4.5.6.0.xml
--  Ran at: 11/27/15 1:19 PM
--  Liquibase version: 2.0.5
--  *********************************************************************

--  Changeset /opt/liquibase/data/orchestra_4.5.6.0.xml::change-4.5.6.0-1::akn::(Checksum: 6:3a942c9ffce8da230df053e827a64f99)
CREATE TABLE ORC_REST_SVC_CLIENT (RSC_SCENARIO VARCHAR(250) NULL, RSC_NAME VARCHAR(250) NULL, RSC_DATA LONGBLOB NULL, RSC_DEPLOYED_AT datetime NULL, RSC_UNIQUE_NAME VARCHAR(250) NOT NULL, CONSTRAINT PK_ORC_SVC_CLIENT PRIMARY KEY (RSC_UNIQUE_NAME)) ENGINE= innodb;

CREATE INDEX IDX_ORC_RSVC_SCENARIO ON ORC_REST_SVC_CLIENT(RSC_SCENARIO);

--  Changeset /opt/liquibase/data/orchestra_4.5.6.0.xml::change-4.5.6.0-2::akn::(Checksum: 6:6a0f0aa5d6ddc859dceb92c7b2f7e3be)
CREATE INDEX IDX_ORC_PROCESS_MODELLS_SCEN ON ORC_PROCESS_MODELLS(PMO_SCENARIO);

CREATE INDEX IDX_ORC_CHANNEL_SCEN ON ORC_CHANNEL(CHA_SCENARIO);

CREATE INDEX IDX_ORC_CONTENT_MAPPING_SCEN ON ORC_CONTENT_MAPPING(CMA_SCENARIO);

CREATE INDEX IDX_ORC_MESSAGE_MAPPING_SCEN ON ORC_MESSAGE_MAPPING(MMA_SCENARIO);

CREATE INDEX IDX_ORC_CONTENT_TYPE_SCEN ON ORC_CONTENT_TYPE(CTY_SCENARIO);

CREATE INDEX IDX_ORC_XML_SCHEMA_SCEN ON ORC_XML_SCHEMA(XSC_SCENARIO);

CREATE INDEX IDX_ORC_MESSAGE_INTERFACE_SCEN ON ORC_MESSAGE_INTERFACE(MIN_SCENARIO);

CREATE INDEX IDX_ORC_LANDSCAPE_SCEN ON ORC_LANDSCAPE(LAN_SCENARIO);

CREATE INDEX IDX_ORC_ARCHIVE_SCEN ON ORC_ARCHIVE(ARC_SCENARIO);

CREATE INDEX IDX_ORC_JAVA_CLASS_SCEN ON ORC_JAVA_CLASS(JCL_SCENARIO);

CREATE INDEX IDX_ORC_SVC_PROVIDER_SCEN ON ORC_SVC_PROVIDER(SPR_SCENARIO);

CREATE INDEX IDX_ORC_PRT_PARTNERCONFIG_SCEN ON ORC_PRT_PARTNERCONFIG(PRT_SCENARIO);

CREATE INDEX IDX_ORC_LOOKUPTABLE_SCEN ON ORC_LOOKUPTABLE(LUT_SCENARIO);

