-- Improvement for better deployment

CREATE TABLE ORC_DEPLOYMENT_LIFECYCLE_JOB (
DLJ_IDENT varchar(50) NOT NULL,
DLJ_SCENARIO varchar(255) NOT NULL,
DLJ_TYPE varchar(255) NOT NULL,
DLJ_PROCESSMODELL varchar(255) NULL,
DLJ_SNAPSHOT int NULL,
DLJ_EXT_COL1 varchar(255) NULL,
DLJ_EXT_COL2 varchar(255) NULL,
DLJ_NODE varchar(255) NULL);

CREATE TABLE ORC_SNAPSHOT_DELETION (
SDE_TABLE_NAME varchar(256) NULL,
SDE_SNAPSHOT_TOKEN bigint NULL,
SDE_SNAPSHOT_KEY varchar(256) NULL,
SDE_NODE_ID varchar(256) NULL);

ALTER TABLE ORC_PROCESS_ARBORT ADD
  PRA_STARTUP_COUNT int(32);
  
ALTER TABLE ORC_PROCESS_ARBORT ADD
  PRA_DELETE_SNAPSHOT int(32);
  
ALTER TABLE ORC_PROCESS_STATE ADD
  PRS_UNLOCK_PENDING int(2);
  
ALTER TABLE ORC_PROCESS_STATE ADD
  PRS_UPDATE_VERSION int(32);
  
ALTER TABLE ORC_PROCESSINSTANCE_STATE ADD
  PRS_SNAPSHOT_TOKEN int(32);
  
ALTER TABLE ORC_PROCESSINSTANCE_STATE ADD
  PRS_HAS_CALLBACK int(2);
