-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.5.2.0.xml
-- Ran at: 04.08.14 15:23
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.5.2.0.xml::change-4.5.2.0-01::akn::(Checksum: 6:83dc38a819109a9a62ab7b153b1e411f)
ALTER TABLE ORC_PROCESS_FIFO_SCHED_CACHE DROP PRIMARY KEY;

ALTER TABLE ORC_PROCESS_FIFO_SCHED_CACHE ADD CONSTRAINT PK_PROC_FIFO_CACHE PRIMARY KEY (PFC_PROCESS_REFERENCE);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_FIFO_SCHED_CACHE');

-- Changeset /opt/liquibase/data/orchestra_4.5.2.0.xml::change-4.5.2.0-02::akn::(Checksum: 6:16d671fef4601c41d3bdf205be2869b4)
UPDATE ORC_SCENARIO_DOC SET SDO_SCENARIO = 'ORC' WHERE SDO_SCENARIO IS NULL;

ALTER TABLE ORC_SCENARIO_DOC ALTER COLUMN  SDO_SCENARIO SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SCENARIO_DOC');

UPDATE ORC_SCENARIO_DOC SET SDO_NAME = 'ORC' WHERE SDO_NAME IS NULL;

ALTER TABLE ORC_SCENARIO_DOC ALTER COLUMN  SDO_NAME SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SCENARIO_DOC');

ALTER TABLE ORC_SCENARIO_DOC ADD CONSTRAINT PK_SCENARIO_DOC PRIMARY KEY (SDO_SCENARIO, SDO_NAME);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SCENARIO_DOC');

-- Changeset /opt/liquibase/data/orchestra_4.5.2.0.xml::change-4.5.2.0-09::akn::(Checksum: 6:8da24220f9084030be61c658efb6f015)
DROP INDEX IDX_ORC_EVT_LOCAL_VAR_VALUE;

DROP INDEX IDX_ORC_EVT_PROCESS_VAR_VALUE;

-- Changeset /opt/liquibase/data/orchestra_4.5.2.0.xml::change-4.5.2.0-10::akn::(Checksum: 6:16ff7b8691b02e0a394237a58e6bca7e)
ALTER TABLE ORC_EVT_PROCESS_VARIABLES ALTER COLUMN EVV_VALUE SET DATA TYPE VARCHAR(1024);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_EVT_PROCESS_VARIABLES');

ALTER TABLE ORC_EVT_LOCAL_VARIABLES ALTER COLUMN EVV_VALUE SET DATA TYPE VARCHAR(1024);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_EVT_LOCAL_VARIABLES');

