db2 REORG TABLE arc_dbs_page
db2 REORG TABLE arc_event_error_context
db2 REORG TABLE arc_event_process
db2 REORG TABLE arc_event_process_token
db2 REORG TABLE arc_event_scenario_context
db2 REORG TABLE arc_event_system
db2 REORG TABLE arc_evt_local_variables
db2 REORG TABLE arc_evt_process_variables
db2 REORG TABLE arc_message
db2 REORG TABLE arc_message_data
db2 REORG TABLE arc_message_properties
db2 REORG TABLE arc_process_ext_business_keys
db2 REORG TABLE orc_adapter_state
db2 REORG TABLE orc_alert_data
db2 REORG TABLE orc_archive
db2 REORG TABLE orc_business_calendar
db2 REORG TABLE orc_business_calendar_entry
db2 REORG TABLE orc_business_transaction
db2 REORG TABLE orc_channel
db2 REORG TABLE orc_cluster_environment
db2 REORG TABLE orc_cluster_lock
db2 REORG TABLE orc_cluster_lock_state
db2 REORG TABLE orc_content_mapping
db2 REORG TABLE orc_content_type
db2 REORG TABLE orc_dbs_page


db2 REORG TABLE orc_esb_router
db2 REORG TABLE orc_esb_signal_state
db2 REORG TABLE orc_esb_tcp_cell
db2 REORG TABLE orc_esb_topic_state
db2 REORG TABLE orc_event

db2 REORG TABLE orc_event_error_context
db2 REORG TABLE orc_event_process
db2 REORG TABLE orc_event_process_token
db2 REORG TABLE orc_event_scenario_context

db2 REORG TABLE orc_event_system
db2 REORG TABLE orc_evt_local_variables
db2 REORG TABLE orc_evt_process_variables

db2 REORG TABLE orc_ext_archive
db2 REORG TABLE orc_ext_archive_error
db2 REORG TABLE orc_global_transaction
db2 REORG TABLE orc_java_class

db2 REORG TABLE orc_kpi_dim_value
db2 REORG TABLE orc_kpi_instance
db2 REORG TABLE orc_kpi_value
db2 REORG TABLE orc_landscape
db2 REORG TABLE orc_lookuptable
db2 REORG TABLE orc_lta_message
db2 REORG TABLE orc_lta_message_list
db2 REORG TABLE orc_lta_process_bus_event
db2 REORG TABLE orc_lta_process_ext_bsns_keys
db2 REORG TABLE orc_lta_process_overview
db2 REORG TABLE orc_lta_process_state
db2 REORG TABLE orc_message
db2 REORG TABLE orc_message_data
db2 REORG TABLE orc_message_interface
db2 REORG TABLE orc_message_list
db2 REORG TABLE orc_message_list_entry
db2 REORG TABLE orc_message_list_entry_prop
db2 REORG TABLE orc_message_list_index
db2 REORG TABLE orc_message_mapping
db2 REORG TABLE orc_message_properties
db2 REORG TABLE orc_message_referers
db2 REORG TABLE orc_message_referers_unlock
db2 REORG TABLE orc_message_type
db2 REORG TABLE orc_monitor_nodes
db2 REORG TABLE orc_monitor_settings
db2 REORG TABLE orc_monitor_tablesettings
db2 REORG TABLE orc_process_arbort
db2 REORG TABLE orc_process_bus_event
db2 REORG TABLE orc_process_execution
db2 REORG TABLE orc_process_ext_business_keys
db2 REORG TABLE orc_process_fifo_sched_cache
db2 REORG TABLE orc_process_fifo_schedule
db2 REORG TABLE orc_process_mode
db2 REORG TABLE orc_process_modells
db2 REORG TABLE orc_process_modells_hist
db2 REORG TABLE orc_process_overview
db2 REORG TABLE orc_process_runtime_state
db2 REORG TABLE orc_process_scenario
db2 REORG TABLE orc_process_scenario_history
db2 REORG TABLE orc_process_state
db2 REORG TABLE orc_process_token_state
db2 REORG TABLE orc_process_wait_list
db2 REORG TABLE orc_processinstance_state
db2 REORG TABLE orc_prs_description
db2 REORG TABLE orc_prt_partnerconfig
db2 REORG TABLE orc_queue_topic_state
db2 REORG TABLE orc_recovery_data
db2 REORG TABLE orc_scenario_doc
db2 REORG TABLE orc_sec_credential_v2

db2 REORG TABLE orc_sec_group_roles_v2
db2 REORG TABLE orc_sec_group_v2
db2 REORG TABLE orc_sec_keystore_v2

db2 REORG TABLE orc_sec_role_v2
db2 REORG TABLE orc_sec_truststore_v2

db2 REORG TABLE orc_sec_user_auth_methods_v2
db2 REORG TABLE orc_sec_user_certificate
db2 REORG TABLE orc_sec_user_group_v2
db2 REORG TABLE orc_sec_user_pkcs12

db2 REORG TABLE orc_sec_user_roles_v2
db2 REORG TABLE orc_sec_user_ssh
db2 REORG TABLE orc_sec_user_state
db2 REORG TABLE orc_sequence_counter
db2 REORG TABLE orc_server_settings

db2 REORG TABLE orc_svc_declaration
db2 REORG TABLE orc_svc_provider
db2 REORG TABLE orc_timing_data
db2 REORG TABLE orc_topic_queue
db2 REORG TABLE orc_transaction
db2 REORG TABLE orc_transaction_branch
db2 REORG TABLE orc_transaction_log_entry
db2 REORG TABLE orc_user_pwd_table
db2 REORG TABLE orc_userscenariomap
db2 REORG TABLE orc_work_queue
db2 REORG TABLE orc_xml_schema
db2 REORG TABLE qrtz_blob_triggers
db2 REORG TABLE qrtz_calendars
db2 REORG TABLE qrtz_cron_triggers
db2 REORG TABLE qrtz_fired_triggers
db2 REORG TABLE qrtz_job_details
db2 REORG TABLE qrtz_job_listeners
db2 REORG TABLE qrtz_locks
db2 REORG TABLE qrtz_paused_trigger_grps
db2 REORG TABLE qrtz_scheduler_state
db2 REORG TABLE qrtz_simple_triggers
db2 REORG TABLE qrtz_trigger_listeners
db2 REORG TABLE qrtz_triggers
db2 REORG TABLE ORC_COMMIT_DESC
