
ALTER TABLE ORC_MESSAGE_LIST_ENTRY 
        ADD MLE_REFERENCE    VARCHAR(40);
GO

UPDATE ORC_MESSAGE_LIST_ENTRY 
   SET MLE_REFERENCE = convert(varchar(18), MLE_ID) + '_' + convert(varchar(10),MLE_INDEX);
GO

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP 
        ADD MLP_REFERENCE    VARCHAR(40);
GO

UPDATE ORC_MESSAGE_LIST_ENTRY_PROP 
   SET MLP_REFERENCE = convert(varchar(18), MLP_ID) + '_' + convert(varchar(10),MLP_INDEX);
GO

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP 
       DROP COLUMN MLP_INDEX;
GO

CREATE TABLE ORC_MESSAGE_LIST_INDEX 
(
	MLI_ID           NUMERIC(18),
	MLI_REFERENCE    VARCHAR(40),
	MLI_INDEX        NUMERIC(10)
);

INSERT INTO ORC_MESSAGE_LIST_INDEX( MLI_ID, MLI_REFERENCE, MLI_INDEX ) 
SELECT MLE_ID, MLE_REFERENCE, MLE_INDEX 
  FROM ORC_MESSAGE_LIST_ENTRY;
GO

ALTER TABLE ORC_MESSAGE_LIST_ENTRY 
DROP COLUMN MLE_INDEX;
GO

INSERT INTO ORC_SEC_ROLE_V2 (OSR_SCENARIO, OSR_IDENTIFIER, OSR_DESC)
VALUES ('RUNTIME', 'RUNTIME:WEBDAV.SUPERUSER', NULL);
GO

CREATE TABLE ORC_PRS_DESCRIPTION
(
  PRS_SCENARIO     VARCHAR(250),
  PRS_NAME         VARCHAR(250),
  PRS_DATA         IMAGE,
  PRS_DEPLOYED_AT  DATETIME,
  PRS_UNIQUE_NAME  VARCHAR(250) NOT NULL
);
GO

CREATE UNIQUE INDEX UIDX_ORC_PRS_DESCRIPTION ON ORC_PRS_DESCRIPTION(PRS_SCENARIO, PRS_NAME);
GO

ALTER TABLE ORC_PRS_DESCRIPTION ADD CONSTRAINT PK_ORC_PRS_DESCRIPTION PRIMARY KEY (PRS_UNIQUE_NAME);
GO
