-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: ./data/orchestra_master_4.4.0.0.xml
-- Ran at: 08.04.13 16:22
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-50::akn (generated)::(Checksum: 3:402c8bfcfcbd423bcfb4c5805ba43397)
ALTER TABLE [dbo].[ORC_MESSAGE_REFERERS] ADD [MRE_FLAG] CHAR(1)
GO

ALTER TABLE [dbo].[ORC_MESSAGE_REFERERS] ADD [MRE_REQ_LEASE_TIME] INT
GO

ALTER TABLE [dbo].[ORC_MESSAGE] ADD [MES_LEASE_TIME] DATETIME
GO

ALTER TABLE [dbo].[ORC_MESSAGE_LIST] ADD [MLI_LEASE_TIME] DATETIME
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-51::akn (generated)::(Checksum: 3:d63e24bb22090aa5f3f02fa7edc8e28f)
ALTER TABLE [dbo].[ORC_PROCESS_SCENARIO] ADD [PSC_VERSION] VARCHAR(255)
GO

ALTER TABLE [dbo].[ORC_PROCESS_SCENARIO] ADD [PSC_SCENARIO_IMAGE] VARBINARY(MAX)
GO

ALTER TABLE [dbo].[ORC_PROCESS_STATE] ADD [PRS_VERSION_TAG] VARCHAR(255)
GO

ALTER TABLE [dbo].[ORC_PROCESS_STATE] ADD [PRS_CREATE_TIME] DATETIME
GO

UPDATE [dbo].[ORC_PROCESS_STATE] SET [PRS_CREATE_TIME] = PRS_START_TIME
GO

ALTER TABLE [dbo].[ORC_PROCESS_STATE] ALTER COLUMN [PRS_CREATE_TIME] DATETIME NOT NULL
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-53::akn (generated)::(Checksum: 3:97aea6d7afd6b027d0a5eec904d0170a)
CREATE TABLE [dbo].[ORC_PROCESS_SCENARIO_HISTORY] ([PSC_UNIQUE_NAME] VARCHAR(255) NOT NULL, [PSC_NAME] VARCHAR(255) NOT NULL, [PSC_VERSION] VARCHAR(255) NOT NULL, [PSC_DESCRIPTION] VARCHAR(500), [PSC_DEPLOYED_AT] DATETIME, [PSC_USER] VARCHAR(255), [PSC_SCENARIO_IMAGE] VARBINARY(MAX))
GO
ALTER TABLE [dbo].[ORC_PROCESS_SCENARIO_HISTORY] SET (LOCK_ESCALATION = TABLE);
GO

ALTER TABLE [dbo].[ORC_PROCESS_SCENARIO_HISTORY] ADD CONSTRAINT [PK_ORC_PROCESS_SCENARIO_HIST] PRIMARY KEY ([PSC_UNIQUE_NAME], [PSC_VERSION]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS = OFF)
GO

CREATE TABLE [dbo].[ORC_PROCESS_MODELLS_HIST] ([PMO_UNIQUE_NAME] VARCHAR(255) NOT NULL, [PMO_SCENARIO] VARCHAR(255) NOT NULL, [PMO_VERSION] VARCHAR(255) NOT NULL, [PMO_NAME] VARCHAR(255), [PMO_DATA] VARBINARY(MAX), [PMO_DEPLOYED_AT] DATETIME NOT NULL)
GO
ALTER TABLE [dbo].[ORC_PROCESS_MODELLS_HIST] SET (LOCK_ESCALATION = TABLE);
GO

ALTER TABLE [dbo].[ORC_PROCESS_MODELLS_HIST] ADD CONSTRAINT [PK_ORC_PROCESS_MODELLS_HIST] PRIMARY KEY ([PMO_UNIQUE_NAME], [PMO_VERSION]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS = OFF)
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-54::akn (generated)::(Checksum: 3:5f3cb517516f017720ceda6c56cd890b)
CREATE TABLE [dbo].[ORC_PROCESS_BUS_EVENT] ([PBE_PROCESSID] VARCHAR(255) NOT NULL, [PBE_EXTERNAL_ELEMENT] VARCHAR(255) NOT NULL, [PBE_ELEMENT_TYPE] VARCHAR(255) NOT NULL, [PBE_GROUP] VARCHAR(255) NOT NULL, [PBE_THROWING] BIT NOT NULL)
GO
ALTER TABLE [dbo].[ORC_PROCESS_BUS_EVENT] SET (LOCK_ESCALATION = TABLE);
GO

INSERT INTO [dbo].[ORC_SEC_ROLE_V2] ([OSR_DESC], [OSR_IDENTIFIER], [OSR_SCENARIO]) VALUES ('KpiMonitoring', 'RUNTIME:KpiViewMonitor', 'RUNTIME')
GO

INSERT INTO [dbo].[ORC_SEC_USER_ROLES_V2] ([OUR_ROLE_ID], [OUR_USER_ID]) VALUES ('KpiViewMonitor', 'RUNTIME:admin')
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-55::akn (generated)::(Checksum: 3:20833246b23aa89fd449a4e8a18b88ea)
DROP VIEW [dbo].[ORC_PROCESS_STATE_BUSINESS_KEY]
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-52::akn (generated)::(Checksum: 3:c378a3e9319db7aca2f2ff3046e2a554)
CREATE VIEW [dbo].[ORC_PROCESS_STATE_V] AS SELECT * FROM ORC_PROCESS_STATE
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-56::akn (generated)::(Checksum: 3:4204b3b897b51a16322b8dfc0528d034)
CREATE VIEW [dbo].[ORC_PROCESS_STATE_BUSINESS_KEY] AS SELECT PRS_PROCESS_ID, PRS_MODELL_ID, PRS_START_TIME, PRS_END_TIME,
				  PRS_STATE, PRS_BUSINESS_KEY, PRS_SCENARIO_ID,
				  PRS_ROOT_TOKEN, PRS_PROCESS_MODEL, PRS_VERSION_TAG, PRS_CREATE_TIME, PEK_PROCESS_ID,
				  PEK_BUSINESS_KEY_NAME, PEK_BUSINESS_KEY
			 FROM orc_process_state, orc_process_ext_business_keys
			WHERE pek_process_id = prs_process_id
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-57::akn (generated)::(Checksum: 3:a16d157efe98486fae6f7b025b075acf)
ALTER TABLE [dbo].[ORC_MONITOR_SETTINGS] DROP COLUMN [ORC_LANGUAGE]
GO

ALTER TABLE [dbo].[ORC_MONITOR_SETTINGS] ADD [ORC_LANGUAGE] VARCHAR(6) NOT NULL CONSTRAINT DF_ORC_MONITOR_SETTINGS_ORC_LANGUAGE DEFAULT 'EN'
GO

ALTER TABLE [dbo].[ORC_SERVER_SETTINGS] ADD [LANGUAGE] VARCHAR(6) NOT NULL CONSTRAINT DF_ORC_SERVER_SETTINGS_LANGUAGE DEFAULT 'EN'
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-58::akn (generated)::(Checksum: 3:9c0c408d474b721b7b620271a333b17a)
CREATE TABLE [dbo].[ORC_MONITOR_NODES] ([OMN_NAME] VARCHAR(255) NOT NULL, [OMN_HOST] VARCHAR(255), [OMN_GROUPNAME] VARCHAR(255), [OMN_SSL] BIT, [OMN_PORT] VARCHAR(255), [OMN_USER_ID] VARCHAR(255), [OMN_PASSWORD] VARCHAR(255), [OMN_LOCAL] BIT, CONSTRAINT [PK_MONITOR_NODES] PRIMARY KEY ([OMN_NAME]))
GO
ALTER TABLE [dbo].[ORC_MONITOR_NODES] SET (LOCK_ESCALATION = TABLE);
GO

INSERT INTO [dbo].[ORC_MONITOR_NODES] ([OMN_LOCAL], [OMN_NAME], [OMN_PORT], [OMN_SSL]) VALUES (1, 'ORC', '0', 0)
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-59::akn (generated)::(Checksum: 3:2831ad58779068abe32d52f2231d5ea6)
CREATE TABLE [dbo].[ORC_KPI_INSTANCE] ([KIN_IDENTIFIER] VARCHAR(50) NOT NULL, [KIN_CLASS_IDENT] VARCHAR(50) NOT NULL, [KIN_OWNER_NODE] VARCHAR(50) NOT NULL, [KIN_ABS_OCCURANCE] BIGINT, [KIN_ABS_LONGVALUE] BIGINT, [KIN_ABS_DOUBLE_VALUE] FLOAT, [KIN_LASTACCESS] DATETIME)
GO
ALTER TABLE [dbo].[ORC_KPI_INSTANCE] SET (LOCK_ESCALATION = TABLE);
GO

CREATE TABLE [dbo].[ORC_KPI_DIM_VALUE] ([KDV_INSTANCEID] VARCHAR(50) NOT NULL, [KDV_NAME] VARCHAR(50) NOT NULL, [KDV_VALUE] VARCHAR(75))
GO
ALTER TABLE [dbo].[ORC_KPI_DIM_VALUE] SET (LOCK_ESCALATION = TABLE);
GO

CREATE TABLE [dbo].[ORC_KPI_VALUE] ([KVA_INSTANCEID] VARCHAR(50) NOT NULL, [KVA_TIMEINDEX] BIGINT NOT NULL, [KVA_OCCURANCE] BIGINT, [KVA_LONGVALUE] BIGINT, [KVA_DOUBLE_VALUE] FLOAT)
GO
ALTER TABLE [dbo].[ORC_KPI_VALUE] SET (LOCK_ESCALATION = TABLE);
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-60::akn (generated)::(Checksum: 3:b81296993fca3b1a324c347326a20b48)
CREATE TABLE [dbo].[ORC_LTA_MESSAGE] ([MES_MESSAGE_ID] VARCHAR(255) NOT NULL, [MES_MESSAGE_TYPE] VARCHAR(255), [MES_CREATED_AT] DATETIME, [MES_TYPE] VARCHAR(255), [MES_REF_COUNT] INT, [MES_LEASE_TIME] DATETIME, [MES_ARCHIVE_INFO] VARCHAR(255))
GO
ALTER TABLE [dbo].[ORC_LTA_MESSAGE] SET (LOCK_ESCALATION = TABLE);
GO

CREATE INDEX [IDX_LTA_MSG_CREATED_AT] ON [dbo].[ORC_LTA_MESSAGE]([MES_CREATED_AT]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX [IDX_LTA_MSG_MESSAGE_ID] ON [dbo].[ORC_LTA_MESSAGE]([MES_MESSAGE_ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE TABLE [dbo].[ORC_LTA_PROCESS_BUS_EVENT] ([LPB_PROCESSID] VARCHAR(255) NOT NULL, [LPB_POS] INT NOT NULL, [LPB_EXTERNAL_ELEMENT] VARCHAR(255) NOT NULL, [LPB_ELEMENT_TYPE] VARCHAR(255) NOT NULL, [LPB_GROUP] VARCHAR(255), [LPB_THROWING] BIT NOT NULL, [LPB_ARCHIVE_DATE] DATETIME)
GO
ALTER TABLE [dbo].[ORC_LTA_PROCESS_BUS_EVENT] SET (LOCK_ESCALATION = TABLE);
GO

CREATE TABLE [dbo].[ORC_LTA_PROCESS_EXT_BSNS_KEYS] ([PEK_PROCESS_ID] VARCHAR(255) NOT NULL, [PEK_BUSINESS_KEY_NAME] VARCHAR(255) NOT NULL, [PEK_BUSINESS_KEY] VARCHAR(255), [PEK_ARCHIVE_DATE] DATETIME)
GO
ALTER TABLE [dbo].[ORC_LTA_PROCESS_EXT_BSNS_KEYS] SET (LOCK_ESCALATION = TABLE);
GO

CREATE INDEX [IDX_LTA_EXT_BK] ON [dbo].[ORC_LTA_PROCESS_EXT_BSNS_KEYS]([PEK_BUSINESS_KEY_NAME], [PEK_BUSINESS_KEY]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO 

CREATE TABLE [dbo].[ORC_LTA_PROCESS_OVERVIEW] ([LPO_SCENARIO_ID] VARCHAR(256), [LPO_PROCESSED] INT, [LPO_ABORTED] INT)
GO
ALTER TABLE [dbo].[ORC_LTA_PROCESS_OVERVIEW] SET (LOCK_ESCALATION = TABLE);
GO

CREATE TABLE [dbo].[ORC_LTA_PROCESS_STATE] ([PRS_PROCESS_ID] VARCHAR(255) NOT NULL, [PRS_MODELL_ID] VARCHAR(255), [PRS_START_TIME] DATETIME, [PRS_END_TIME] DATETIME, [PRS_STATE] INT, [PRS_BUSINESS_KEY] VARCHAR(1024), [PRS_SCENARIO_ID] VARCHAR(256), [PRS_ROOT_TOKEN] VARCHAR(256), [PRS_PROCESS_MODEL] VARCHAR(255), [PRS_VERSION_TAG] VARCHAR(255), [PRS_CREATE_TIME] DATETIME, [PRS_BUSEVENT_TYPE] INT, [PRS_BUSEVENT_REFERENCE] VARCHAR(255), [PRS_BUSEVENT_ALIAS] VARCHAR(255), [PRS_ARCHIVE_DATE] DATETIME, [PRS_ARCHIVE_INFO] VARCHAR(255))
GO
ALTER TABLE [dbo].[ORC_LTA_PROCESS_STATE] SET (LOCK_ESCALATION = TABLE);
GO

CREATE INDEX [IDX_LTA_PROC_STATE_SCENARIO] ON [dbo].[ORC_LTA_PROCESS_STATE]([PRS_SCENARIO_ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX [ORC_LTA_PROCESS_SCENARIO_STATE] ON [dbo].[ORC_LTA_PROCESS_STATE]([PRS_SCENARIO_ID], [PRS_STATE]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-62::akn (generated)::(Checksum: 3:053a9cdde0343f96de5e06495bd91dd7)
CREATE TABLE [dbo].[ORC_ESB_ROUTER] ([ERO_ID] VARCHAR(50) NOT NULL, [ERO_TARGET_CELL] VARCHAR(50), [ERO_HOP_NAME] VARCHAR(50), [ERO_ORCHESTRA_NODE] VARCHAR(50), CONSTRAINT [PK_ESB_ROUTER] PRIMARY KEY ([ERO_ID]))
GO
ALTER TABLE [dbo].[ORC_ESB_ROUTER] SET (LOCK_ESCALATION = TABLE);
GO

CREATE INDEX [IDX_ESB_ROUTER_NODE_TARGET] ON [dbo].[ORC_ESB_ROUTER]([ERO_ORCHESTRA_NODE], [ERO_TARGET_CELL]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE TABLE [dbo].[ORC_ESB_TCP_CELL] ([ETC_CELL_ID] VARCHAR(50) NOT NULL, [ETC_ORCHESTRA_NODE] VARCHAR(50) NOT NULL, [ETC_CELLNAME] VARCHAR(50) NOT NULL, [ETC_ENDPOINT] VARCHAR(50), [ETC_PASSWORD] VARCHAR(50), [ETC_PORT] INT, [ETC_INGOING] BIT NOT NULL, CONSTRAINT [PK_ESB_TCP_CELL] PRIMARY KEY ([ETC_CELL_ID]))
GO
ALTER TABLE [dbo].[ORC_ESB_TCP_CELL] SET (LOCK_ESCALATION = TABLE);
GO

CREATE INDEX [IDX_ESB_TCP_CELL_HOST_CELL] ON [dbo].[ORC_ESB_TCP_CELL]([ETC_ORCHESTRA_NODE], [ETC_CELLNAME]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-63::akn (generated)::(Checksum: 3:7cde7e4466d5ad935a195b701dfba17b)
CREATE INDEX [IDX_PROCESS_BUS_EVENT_1] ON [dbo].[ORC_PROCESS_BUS_EVENT]([PBE_THROWING], [PBE_GROUP]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

CREATE INDEX [IDX_PROCESS_BUS_EVENT_2] ON [dbo].[ORC_PROCESS_BUS_EVENT]([PBE_PROCESSID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-64::akn (generated)::(Checksum: 3:5c1d374b4b0e5641b4759182b28550bc)
ALTER TABLE [dbo].[ORC_USER_PWD_TABLE] ADD [OUP_USERNAME] VARCHAR(255)
GO

UPDATE [dbo].[ORC_USER_PWD_TABLE] SET [OUP_USERNAME] = (select OSC_NAME from ORC_SEC_CREDENTIAL_V2 v where v.OSC_UNIQUE_ID = OUP_USER_ID) WHERE OUP_USER_ID in ( select OSC_UNIQUE_ID from ORC_SEC_CREDENTIAL_V2 where OSC_TYPE = 'TECHNICAL_LOGIN' )
GO

UPDATE [dbo].[ORC_USER_PWD_TABLE] SET [OUP_USERNAME] = (select OSC_IDENTIFIER from ORC_SEC_CREDENTIAL_V2 v where v.OSC_UNIQUE_ID = OUP_USER_ID) WHERE OUP_USER_ID in ( select OSC_UNIQUE_ID from ORC_SEC_CREDENTIAL_V2 where OSC_TYPE <> 'TECHNICAL_LOGIN' )
GO

ALTER TABLE [dbo].[ORC_SEC_CREDENTIAL_V2] DROP COLUMN [OSC_IDENTIFIER]
GO

UPDATE [dbo].[ORC_USER_PWD_TABLE] SET [OUP_SCENARIO] = 'RUNTIME' WHERE OUP_USER_ID like 'RUNTIME:%'
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-65::akn (generated)::(Checksum: 3:4a442d8faa5bd1ec178e5b9914c07563)
UPDATE [dbo].[ORC_MONITOR_SETTINGS] SET [ORC_THEME] = 'standard'
GO

-- Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-66::wli::(Checksum: 3:4e75c7a94b3817678d0655f568f1676b)
UPDATE [dbo].[ORC_PROCESS_SCENARIO] SET [PSC_VERSION] = 'Initial'
GO

insert into ORC_PROCESS_MODELLS_HIST(PMO_SCENARIO, PMO_VERSION, PMO_NAME, PMO_DATA, PMO_DEPLOYED_AT, PMO_UNIQUE_NAME)
			select PMO_SCENARIO, 'Initial', PMO_NAME, PMO_DATA, PMO_DEPLOYED_AT, PMO_UNIQUE_NAME from ORC_PROCESS_MODELLS
GO

insert into ORC_PROCESS_SCENARIO_HISTORY(PSC_UNIQUE_NAME, PSC_NAME, PSC_DESCRIPTION, PSC_DEPLOYED_AT, PSC_USER, PSC_VERSION, PSC_SCENARIO_IMAGE)
			select PSC_UNIQUE_NAME, PSC_NAME, PSC_DESCRIPTION, PSC_DEPLOYED_AT, PSC_USER, 'Initial', PSC_SCENARIO_IMAGE from ORC_PROCESS_SCENARIO
GO
