
CREATE TABLE ORC_EVENT_ERROR_CONTEXT
(
  ERC_ID         bigint				Not null Auto_Increment,
  constraint PK_ORC_EVENT_ERROR_CONTEXT primary key (ERC_ID),
  ERC_EXC_TYPE   VARCHAR(255),
  ERC_ACTION     VARCHAR(255),
  ERC_MESSAGE    VARCHAR(255),
  ERC_CLASSNAME  VARCHAR(255),
  ERC_METHOD     VARCHAR(255),
  ERC_FILE       VARCHAR(255),
  ERC_LINE       bigint,
  ERC_STACK      VARCHAR(1536)
);

CREATE TABLE ORC_EVENT_SCENARIO_CONTEXT
(
  ECO_ID            bigint			Not null Auto_Increment,
  constraint PK_ORC_EVENT_SCENARIO_CONTEXT primary key (ECO_ID),
  ECO_DERIVED_TYPE  VARCHAR(512)    Not null,
  ECO_REFERENCE     VARCHAR(512),
  ECO_NAME          VARCHAR(512),
  ECO_TYPE          VARCHAR(512),
  ECO_SUBTYPE       VARCHAR(512),
  ECO_ACT_NAME      VARCHAR(512),
  ECO_ACT_ID        VARCHAR(512),
  ECO_ACT_TYPE      VARCHAR(512),
  ECO_RETRY         bigint,
  ECO_MAX_RETRIES   bigint
);


ALTER TABLE ORC_EVENT_SYSTEM add
(
  EVT_SCEN_REF        VARCHAR(255),
  EVT_SCEN_NAME       VARCHAR(255),
  EVT_SCEN_DESC       VARCHAR(255),
  EVT_SCEN_PROCESSOR  bigint,
  EVT_SCEN_INITIATOR  bigint,
  EVT_ERROR_CONTEXT   bigint
);

ALTER TABLE ORC_EVENT_SYSTEM CHANGE EVT_DESCRIPTION EVT_DESCRIPTION VARCHAR(512);


ALTER TABLE ORC_PROCESS_STATE ADD (
  PRS_BUSINESS_KEY  VARCHAR(256),
  PRS_BUSINESS_KEY_NAME  VARCHAR(256),
  PRS_SCENARIO_ID   VARCHAR(256),
  PRS_ROOT_TOKEN    VARCHAR(256)
);


CREATE TABLE ORC_TIMING_DATA (
	OTD_IDENTIFIER VARCHAR(255) not null, 
	OTD_OWNER_TYPE VARCHAR(255), 
	OTD_OWNER_NAME VARCHAR(255), 
	OTD_DETAIL_TYPE VARCHAR(255), 
	OTD_DETAIL_NAME VARCHAR(255), 
	OTD_TIMING_TEXT VARCHAR(255), 
	OTD_PAUSED bigint, 
	OTD_TIMING BLOB
);

ALTER TABLE ORC_TIMING_DATA ADD CONSTRAINT PK_ORC_TIMING_DATA PRIMARY KEY (OTD_IDENTIFIER);

CREATE TABLE ORC_MONITOR_SETTINGS
(
  ORC_USERID            VARCHAR(255)      NOT NULL,
  ORC_STAGE_LABEL_TEXT  VARCHAR(255),
  ORC_STAGE_LABEL_COLOR VARCHAR(255),
  ORC_LANGUAGE          VARCHAR(255),
  ORC_LOGOFF_PERIODE    bigint
);

CREATE TABLE ORC_MONITOR_TABLESETTINGS
(
	ORC_PARENT_USERID VARCHAR(255) NOT NULL,
	ORC_TABLECLASS VARCHAR(255) NOT NULL,
	ORC_AUTOREFRESH bigint,
	ORC_MAXELEMENTS bigint,
	ORC_REFRESHINTERVAL bigint,
	ORC_DEFAULT_SORT_COLUMN bigint,
	ORC_DEFAULT_SORT_ASCENDING bigint,
	ORC_COLUMN_PATTERN VARCHAR(255)
);

insert into ORC_SEC_GROUP_V2 (OSG_SCENARIO, OSG_IDENTIFIER, OSG_DESC) values ('RUNTIME', 'RUNTIME:Timer', NULL);

insert into ORC_SEC_ROLE_V2 (OSR_SCENARIO, OSR_IDENTIFIER, OSR_DESC) values ('RUNTIME', 'RUNTIME:TimerView', NULL);
insert into ORC_SEC_ROLE_V2 (OSR_SCENARIO, OSR_IDENTIFIER, OSR_DESC) values ('RUNTIME', 'RUNTIME:TimerUpdate', NULL);
insert into ORC_SEC_ROLE_V2 (OSR_SCENARIO, OSR_IDENTIFIER, OSR_DESC) values ('RUNTIME', 'RUNTIME:TimerPause', NULL);

insert into ORC_SEC_GROUP_ROLES_V2 (OGR_GROUP_ID, OGR_ROLE_ID) values ('RUNTIME:Timer', 'TimerView');
insert into ORC_SEC_GROUP_ROLES_V2 (OGR_GROUP_ID, OGR_ROLE_ID) values ('RUNTIME:Timer', 'TimerUpdate');
insert into ORC_SEC_GROUP_ROLES_V2 (OGR_GROUP_ID, OGR_ROLE_ID) values('RUNTIME:Timer', 'TimerPause');






insert into ORC_CLUSTER_LOCK(ORC_LOCK_NAME, ORC_LOCK_STATE, ORC_LOCK_OWNER, ORC_LOCK_SCENARIO) Values ('TIMER', NULL, NULL, 'GLOBAL');




insert into ORC_SEC_USER_ROLES_V2(OUR_USER_ID, OUR_ROLE_ID) values ('RUNTIME:admin', 'TimerView');
insert into ORC_SEC_USER_ROLES_V2(OUR_USER_ID, OUR_ROLE_ID) values ('RUNTIME:admin', 'TimerUpdate');
insert into ORC_SEC_USER_ROLES_V2(OUR_USER_ID, OUR_ROLE_ID) values ('RUNTIME:admin', 'TimerPause');

commit;
