--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: ./data/orchestra_master_4.4.0.0.xml
--  Ran at: 09.04.13 17:06
--  Against: ORCHESTRA@localhost@jdbc:mysql://localhost:3306/orchestra5
--  Liquibase version: 2.0.5
--  *********************************************************************

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-50::akn (generated)::(Checksum: 3:402c8bfcfcbd423bcfb4c5805ba43397)
ALTER TABLE `ORC_MESSAGE_REFERERS` ADD `MRE_FLAG` CHAR(1);
ALTER TABLE `ORC_MESSAGE_REFERERS` ADD `MRE_REQ_LEASE_TIME` INT;
ALTER TABLE `ORC_MESSAGE` ADD `MES_LEASE_TIME` TIMESTAMP NULL;
ALTER TABLE `ORC_MESSAGE_LIST` ADD `MLI_LEASE_TIME` TIMESTAMP NULL;

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-51::akn (generated)::(Checksum: 3:d63e24bb22090aa5f3f02fa7edc8e28f)
ALTER TABLE `ORC_PROCESS_SCENARIO` ADD `PSC_VERSION` VARCHAR(255);
ALTER TABLE `ORC_PROCESS_SCENARIO` ADD `PSC_SCENARIO_IMAGE` LONGBLOB;
ALTER TABLE `ORC_PROCESS_STATE` ADD `PRS_VERSION_TAG` VARCHAR(255);
ALTER TABLE `ORC_PROCESS_STATE` ADD `PRS_CREATE_TIME` TIMESTAMP NULL;
UPDATE `ORC_PROCESS_STATE` SET `PRS_CREATE_TIME` = PRS_START_TIME;
ALTER TABLE `ORC_PROCESS_STATE` MODIFY `PRS_CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-53::akn (generated)::(Checksum: 3:97aea6d7afd6b027d0a5eec904d0170a)
CREATE TABLE `ORC_PROCESS_SCENARIO_HISTORY` (`PSC_UNIQUE_NAME` VARCHAR(255) NOT NULL, `PSC_NAME` VARCHAR(255) NOT NULL, `PSC_VERSION` VARCHAR(255) NOT NULL, `PSC_DESCRIPTION` VARCHAR(500) NULL, `PSC_DEPLOYED_AT` TIMESTAMP, `PSC_USER` VARCHAR(255) NULL, `PSC_SCENARIO_IMAGE` LONGBLOB NULL);
ALTER TABLE `ORC_PROCESS_SCENARIO_HISTORY` ADD PRIMARY KEY (`PSC_UNIQUE_NAME`, `PSC_VERSION`);
CREATE TABLE `ORC_PROCESS_MODELLS_HIST` (`PMO_UNIQUE_NAME` VARCHAR(255) NOT NULL, `PMO_SCENARIO` VARCHAR(255) NOT NULL, `PMO_VERSION` VARCHAR(255) NOT NULL, `PMO_NAME` VARCHAR(255) NULL, `PMO_DATA` LONGBLOB NULL, `PMO_DEPLOYED_AT` TIMESTAMP NOT NULL);
ALTER TABLE `ORC_PROCESS_MODELLS_HIST` ADD PRIMARY KEY (`PMO_UNIQUE_NAME`, `PMO_VERSION`);

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-54::akn (generated)::(Checksum: 3:78ebd9bb0ec74d6961e9debe03af955d)
CREATE TABLE `ORC_PROCESS_BUS_EVENT` (`PBE_PROCESSID` VARCHAR(255) NOT NULL, `PBE_EXTERNAL_ELEMENT` VARCHAR(255) NOT NULL, `PBE_ELEMENT_TYPE` VARCHAR(255) NOT NULL, `PBE_GROUP` VARCHAR(255) NOT NULL, `PBE_THROWING` TINYINT(1) NOT NULL);
INSERT INTO `ORC_SEC_ROLE_V2` (`OSR_DESC`, `OSR_IDENTIFIER`, `OSR_SCENARIO`) VALUES ('KpiMonitoring', 'RUNTIME:KpiViewMonitor', 'RUNTIME');
INSERT INTO `ORC_SEC_USER_ROLES_V2` (`OUR_ROLE_ID`, `OUR_USER_ID`) VALUES ('KpiViewMonitor', 'RUNTIME:admin');
INSERT INTO `ORC_SEC_ROLE_V2` (`OSR_DESC`, `OSR_IDENTIFIER`, `OSR_SCENARIO`) VALUES ('Restart of process instances', 'RUNTIME:RestartProcess', 'RUNTIME');
INSERT INTO `ORC_SEC_USER_ROLES_V2` (`OUR_ROLE_ID`, `OUR_USER_ID`) VALUES ('RestartProcess', 'RUNTIME:admin');

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-55::akn (generated)::(Checksum: 3:20833246b23aa89fd449a4e8a18b88ea)
DROP VIEW `ORC_PROCESS_STATE_BUSINESS_KEY`;

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-52::akn (generated)::(Checksum: 3:c378a3e9319db7aca2f2ff3046e2a554)
CREATE SQL SECURITY INVOKER VIEW `ORC_PROCESS_STATE_V` AS SELECT * FROM ORC_PROCESS_STATE;

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-56::akn (generated)::(Checksum: 3:4204b3b897b51a16322b8dfc0528d034)
CREATE SQL SECURITY INVOKER VIEW `ORC_PROCESS_STATE_BUSINESS_KEY` AS SELECT PRS_PROCESS_ID, PRS_MODELL_ID, PRS_START_TIME, PRS_END_TIME,
				  PRS_STATE, PRS_BUSINESS_KEY, PRS_SCENARIO_ID,
				  PRS_ROOT_TOKEN, PRS_PROCESS_MODEL, PRS_VERSION_TAG, PRS_CREATE_TIME, PEK_PROCESS_ID,
				  PEK_BUSINESS_KEY_NAME, PEK_BUSINESS_KEY
			 FROM ORC_PROCESS_STATE, ORC_PROCESS_EXT_BUSINESS_KEYS
			WHERE PEK_PROCESS_ID = PRS_PROCESS_ID;

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-57::akn (generated)::(Checksum: 3:a16d157efe98486fae6f7b025b075acf)
ALTER TABLE `ORC_MONITOR_SETTINGS` DROP COLUMN `ORC_LANGUAGE`;
ALTER TABLE `ORC_MONITOR_SETTINGS` ADD `ORC_LANGUAGE` VARCHAR(6) NOT NULL DEFAULT 'EN';
ALTER TABLE `ORC_SERVER_SETTINGS` ADD `LANGUAGE` VARCHAR(6) NOT NULL DEFAULT 'EN';

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-58::akn (generated)::(Checksum: 3:9c0c408d474b721b7b620271a333b17a)
CREATE TABLE `ORC_MONITOR_NODES` (`OMN_NAME` VARCHAR(255) NOT NULL, `OMN_HOST` VARCHAR(255) NULL, `OMN_GROUPNAME` VARCHAR(255) NULL, `OMN_SSL` TINYINT(1) NULL, `OMN_PORT` VARCHAR(255) NULL, `OMN_USER_ID` VARCHAR(255) NULL, `OMN_PASSWORD` VARCHAR(255) NULL, `OMN_LOCAL` TINYINT(1) NULL, CONSTRAINT `PK_MONITOR_NODES` PRIMARY KEY (`OMN_NAME`));
INSERT INTO `ORC_MONITOR_NODES` (`OMN_LOCAL`, `OMN_NAME`, `OMN_PORT`, `OMN_SSL`) VALUES (1, 'ORC', '0', 0);

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-59::akn (generated)::(Checksum: 3:2831ad58779068abe32d52f2231d5ea6)
CREATE TABLE `ORC_KPI_INSTANCE` (`KIN_IDENTIFIER` VARCHAR(50) NOT NULL, `KIN_CLASS_IDENT` VARCHAR(50) NOT NULL, `KIN_OWNER_NODE` VARCHAR(50) NOT NULL, `KIN_ABS_OCCURANCE` BIGINT NULL, `KIN_ABS_LONGVALUE` BIGINT NULL, `KIN_ABS_DOUBLE_VALUE` FLOAT NULL, `KIN_LASTACCESS` DATETIME NULL);
CREATE TABLE `ORC_KPI_DIM_VALUE` (`KDV_INSTANCEID` VARCHAR(50) NOT NULL, `KDV_NAME` VARCHAR(50) NOT NULL, `KDV_VALUE` VARCHAR(75) NULL);
CREATE TABLE `ORC_KPI_VALUE` (`KVA_INSTANCEID` VARCHAR(50) NOT NULL, `KVA_TIMEINDEX` BIGINT NOT NULL, `KVA_OCCURANCE` BIGINT NULL, `KVA_LONGVALUE` BIGINT NULL, `KVA_DOUBLE_VALUE` FLOAT NULL);

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-60::akn (generated)::(Checksum: 3:b81296993fca3b1a324c347326a20b48)
CREATE TABLE `ORC_LTA_MESSAGE` (`MES_MESSAGE_ID` VARCHAR(255) NOT NULL, `MES_MESSAGE_TYPE` VARCHAR(255) NULL, `MES_CREATED_AT` DATETIME NULL, `MES_TYPE` VARCHAR(255) NULL, `MES_REF_COUNT` INT NULL, `MES_LEASE_TIME` DATETIME NULL, `MES_ARCHIVE_INFO` VARCHAR(255) NULL);
CREATE INDEX `IDX_LTA_MSG_CREATED_AT` ON `ORC_LTA_MESSAGE`(`MES_CREATED_AT`);
CREATE INDEX `IDX_LTA_MSG_MESSAGE_ID` ON `ORC_LTA_MESSAGE`(`MES_MESSAGE_ID`);
CREATE TABLE `ORC_LTA_PROCESS_BUS_EVENT` (`LPB_PROCESSID` VARCHAR(255) NOT NULL, `LPB_POS` INT NOT NULL, `LPB_EXTERNAL_ELEMENT` VARCHAR(255) NOT NULL, `LPB_ELEMENT_TYPE` VARCHAR(255) NOT NULL, `LPB_GROUP` VARCHAR(255) NULL, `LPB_THROWING` TINYINT(1) NOT NULL, `LPB_ARCHIVE_DATE` DATETIME NULL);
CREATE TABLE `ORC_LTA_PROCESS_EXT_BSNS_KEYS` (`PEK_PROCESS_ID` VARCHAR(255) NOT NULL, `PEK_BUSINESS_KEY_NAME` VARCHAR(255) NOT NULL, `PEK_BUSINESS_KEY` VARCHAR(255) NULL, `PEK_ARCHIVE_DATE` DATETIME NULL);
CREATE INDEX `IDX_LTA_EXT_BK` ON `ORC_LTA_PROCESS_EXT_BSNS_KEYS`(`PEK_BUSINESS_KEY_NAME`, `PEK_BUSINESS_KEY`);
CREATE TABLE `ORC_LTA_PROCESS_OVERVIEW` (`LPO_SCENARIO_ID` VARCHAR(256) NULL, `LPO_PROCESSED` INT NULL, `LPO_ABORTED` INT NULL);
CREATE TABLE `ORC_LTA_PROCESS_STATE` (`PRS_PROCESS_ID` VARCHAR(255) NOT NULL, `PRS_MODELL_ID` VARCHAR(255) NULL, `PRS_START_TIME` DATETIME NULL, `PRS_END_TIME` DATETIME NULL, `PRS_STATE` INT NULL, `PRS_BUSINESS_KEY` VARCHAR(1024) NULL, `PRS_SCENARIO_ID` VARCHAR(256) NULL, `PRS_ROOT_TOKEN` VARCHAR(256) NULL, `PRS_PROCESS_MODEL` VARCHAR(255) NULL, `PRS_VERSION_TAG` VARCHAR(255) NULL, `PRS_CREATE_TIME` DATETIME NULL, `PRS_BUSEVENT_TYPE` INT NULL, `PRS_BUSEVENT_REFERENCE` VARCHAR(255) NULL, `PRS_BUSEVENT_ALIAS` VARCHAR(255) NULL, `PRS_ARCHIVE_DATE` DATETIME NULL, `PRS_ARCHIVE_INFO` VARCHAR(255) NULL);
CREATE INDEX `IDX_LTA_PROC_STATE_SCENARIO` ON `ORC_LTA_PROCESS_STATE`(`PRS_SCENARIO_ID`);
CREATE INDEX `ORC_LTA_PROCESS_SCENARIO_STATE` ON `ORC_LTA_PROCESS_STATE`(`PRS_SCENARIO_ID`, `PRS_STATE`);

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-62::akn (generated)::(Checksum: 3:053a9cdde0343f96de5e06495bd91dd7)
CREATE TABLE `ORC_ESB_ROUTER` (`ERO_ID` VARCHAR(50) NOT NULL, `ERO_TARGET_CELL` VARCHAR(50) NULL, `ERO_HOP_NAME` VARCHAR(50) NULL, `ERO_ORCHESTRA_NODE` VARCHAR(50) NULL, CONSTRAINT `PK_ESB_ROUTER` PRIMARY KEY (`ERO_ID`));
CREATE INDEX `IDX_ESB_ROUTER_NODE_TARGET` ON `ORC_ESB_ROUTER`(`ERO_ORCHESTRA_NODE`, `ERO_TARGET_CELL`);
CREATE TABLE `ORC_ESB_TCP_CELL` (`ETC_CELL_ID` VARCHAR(50) NOT NULL, `ETC_ORCHESTRA_NODE` VARCHAR(50) NOT NULL, `ETC_CELLNAME` VARCHAR(50) NOT NULL, `ETC_ENDPOINT` VARCHAR(50) NULL, `ETC_PASSWORD` VARCHAR(50) NULL, `ETC_PORT` INT NULL, `ETC_INGOING` TINYINT(1) NOT NULL, CONSTRAINT `PK_ESB_TCP_CELL` PRIMARY KEY (`ETC_CELL_ID`));
CREATE INDEX `IDX_ESB_TCP_CELL_HOST_CELL` ON `ORC_ESB_TCP_CELL`(`ETC_ORCHESTRA_NODE`, `ETC_CELLNAME`);

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-63::akn (generated)::(Checksum: 3:7cde7e4466d5ad935a195b701dfba17b)
CREATE INDEX `IDX_PROCESS_BUS_EVENT_1` ON `ORC_PROCESS_BUS_EVENT`(`PBE_THROWING`, `PBE_GROUP`);
CREATE INDEX `IDX_PROCESS_BUS_EVENT_2` ON `ORC_PROCESS_BUS_EVENT`(`PBE_PROCESSID`);

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-64::akn (generated)::(Checksum: 3:5c1d374b4b0e5641b4759182b28550bc)
ALTER TABLE `ORC_USER_PWD_TABLE` ADD `OUP_USERNAME` VARCHAR(255);
UPDATE `ORC_USER_PWD_TABLE` SET `OUP_USERNAME` = (select OSC_NAME from ORC_SEC_CREDENTIAL_V2 v where v.OSC_UNIQUE_ID = OUP_USER_ID) WHERE OUP_USER_ID in ( select OSC_UNIQUE_ID from ORC_SEC_CREDENTIAL_V2 where OSC_TYPE = 'TECHNICAL_LOGIN' );
UPDATE `ORC_USER_PWD_TABLE` SET `OUP_USERNAME` = (select OSC_IDENTIFIER from ORC_SEC_CREDENTIAL_V2 v where v.OSC_UNIQUE_ID = OUP_USER_ID) WHERE OUP_USER_ID in ( select OSC_UNIQUE_ID from ORC_SEC_CREDENTIAL_V2 where OSC_TYPE <> 'TECHNICAL_LOGIN' );
ALTER TABLE `ORC_SEC_CREDENTIAL_V2` DROP COLUMN `OSC_IDENTIFIER`;
UPDATE `ORC_USER_PWD_TABLE` SET `OUP_SCENARIO` = 'RUNTIME' WHERE OUP_USER_ID like 'RUNTIME:%';

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-65::akn (generated)::(Checksum: 3:4a442d8faa5bd1ec178e5b9914c07563)
UPDATE `ORC_MONITOR_SETTINGS` SET `ORC_THEME` = 'standard';

--  Changeset ./data/orchestra_master_4.4.0.0.xml::1339688508424-66::wli::(Checksum: 3:4e75c7a94b3817678d0655f568f1676b)
UPDATE `ORC_PROCESS_SCENARIO` SET `PSC_VERSION` = 'Initial';

insert into ORC_PROCESS_MODELLS_HIST(PMO_SCENARIO, PMO_VERSION, PMO_NAME, PMO_DATA, PMO_DEPLOYED_AT, PMO_UNIQUE_NAME)
			select PMO_SCENARIO, 'Initial', PMO_NAME, PMO_DATA, PMO_DEPLOYED_AT, PMO_UNIQUE_NAME from ORC_PROCESS_MODELLS;

insert into ORC_PROCESS_SCENARIO_HISTORY(PSC_UNIQUE_NAME, PSC_NAME, PSC_DESCRIPTION, PSC_DEPLOYED_AT, PSC_USER, PSC_VERSION, PSC_SCENARIO_IMAGE)
			select PSC_UNIQUE_NAME, PSC_NAME, PSC_DESCRIPTION, PSC_DEPLOYED_AT, PSC_USER, 'Initial', PSC_SCENARIO_IMAGE from ORC_PROCESS_SCENARIO;

COMMIT;
