USE [master]
GO

/* create user ORCHESTRA */
CREATE LOGIN [ORCHESTRA] WITH PASSWORD='ORCHESTRA', DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

/* create database ORCHESTRA
 * database starts with 50MB and growth unlimited with 1MB
 * log starts with 10MB and growth with 10% of filesize; max size is 2 GB
 * -->> CHANGE ATTRIBUTE FILENAME !!
 *  
 */
 
/****** Object:  Database [ORCHESTRA]  ******/
CREATE DATABASE [ORCHESTRA] ON  PRIMARY 
( NAME = N'ORCHESTRA', FILENAME = N'C:\Programme\Microsoft SQL Server\MSSQL.1\MSSQL\Data\ORCHESTRA.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ORCHESTRA_log', FILENAME = N'C:\Programme\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\ORCHESTRA_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048MB , FILEGROWTH = 10%)
 COLLATE Latin1_General_CI_AS
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ORCHESTRA].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [ORCHESTRA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ORCHESTRA] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO
ALTER DATABASE [ORCHESTRA] SET RECOVERY SIMPLE
GO

ALTER LOGIN [ORCHESTRA] WITH DEFAULT_DATABASE=[ORCHESTRA]
GO

USE [ORCHESTRA]
GO
CREATE USER [ORCHESTRA] FOR LOGIN [ORCHESTRA] WITH DEFAULT_SCHEMA=[dbo]
GO

USE [ORCHESTRA]
GO
EXEC SP_ADDROLEMEMBER 'db_owner', 'ORCHESTRA'
GO
