





drop index TESTID on ORC_WORK_QUEUE;

create unique index PK_WORK_QUEUE_ID on ORC_WORK_QUEUE(ID);

GO


alter table ORC_QUEUE_TOPIC_STATE add QTS_GROUP VARCHAR(255);

GO


drop INDEX IDX_WORK_QUEUE_TOPIC_ID on ORC_WORK_QUEUE;

create index IDX_WORK_QUEUE_TOPIC_ID on ORC_WORK_QUEUE(ORC_TOPIC_ID, QUEUE_TYPE, STATE);

drop INDEX IDX_WORK_QUEUE_TOPIC_OWNER on ORC_WORK_QUEUE; 

create index IDX_WORK_QUEUE_TOPIC_OWNER on ORC_WORK_QUEUE(ORC_TOPIC_OWNER, QUEUE_TYPE, STATE);


create index IDX_WORK_QUEUE_STATE_TYPE_ID on ORC_WORK_QUEUE(STATE, QUEUE_TYPE, ID);

create index IDX_WORK_QUEUE_STAT_TYP_PRIO on ORC_WORK_QUEUE(STATE, QUEUE_TYPE, PRIORITY desc, ID);

GO


CREATE TABLE ORC_TOPIC_QUEUE (
  ITEMTYPE 		VARCHAR(256) NOT NULL,
  DISCRIMINATOR VARCHAR(256) NOT NULL,
  CREATEDAT 	DATETIME DEFAULT current_timestamp NOT NULL,
  WORKOBJECT 	IMAGE,
  ID 			VARCHAR(30) NOT NULL,
  ACTION 		char(1) DEFAULT 'W',
  NAME 			VARCHAR(256),
  STATE 		INT,
  cluster_node 	VARCHAR(255),
  target_node 	VARCHAR(255),
  node_tick 	VARCHAR(255),
  QUEUE_TYPE 	VARCHAR(1),
  PRIORITY 		INTEGER,
  ORC_TOPIC_OWNER VARCHAR(256),
  ORC_TOPIC_ID	 VARCHAR(256),
  constraint PK_TOPIC_QUEUE_ID PRIMARY KEY (ID)
);

create index IDX_TOPIC_QUEUE_TOPIC_ID on ORC_TOPIC_QUEUE(ORC_TOPIC_ID, QUEUE_TYPE, STATE);

create index IDX_TOPIC_QUEUE_TOPIC_OWNER on ORC_TOPIC_QUEUE(ORC_TOPIC_OWNER, QUEUE_TYPE, STATE);

create index IDX_TOPIC_QUEUE_STATE_TYPE_ID on ORC_TOPIC_QUEUE(STATE, QUEUE_TYPE, ID);

create index IDX_TOPIC_QUEUE_STAT_TYP_PRIO on ORC_TOPIC_QUEUE(STATE, QUEUE_TYPE, PRIORITY, ID);

GO



CREATE TABLE ORC_EXT_ARCHIVE (
  EXA_ID bigint NOT NULL,
  EXA_REQ_MSG_ID VARCHAR(256),
  EXA_REQ_TIMESTAMP DATETIME DEFAULT current_timestamp NOT NULL,
  EXA_REQ_PROPERTY_1 VARCHAR(255),
  EXA_REQ_PROPERTY_2 VARCHAR(255),
  EXA_REQ_PROPERTY_3 VARCHAR(255),
  EXA_REQ_CONTENT IMAGE,
  EXA_RESP_TIMESTAMP DATETIME,
  EXA_RESP_PROPERTY_1 VARCHAR(255),
  EXA_RESP_PROPERTY_2 VARCHAR(255),
  EXA_RESP_PROPERTY_3 VARCHAR(255),
  EXA_RESP_CONTENT IMAGE,
  EXA_TECHNICAL_SOURCE VARCHAR(255),
  EXA_TECHNICAL_NAME VARCHAR(255),
  EXA_RESP_MSG_ID VARCHAR(255),
  constraint PK_EXT_ARCHIVE PRIMARY KEY (EXA_ID)
);


CREATE TABLE ORC_EXT_ARCHIVE_ERROR (
  EAE_ARC_ID bigint NOT NULL,
  ERC_EXC_TYPE VARCHAR(255),
  ERC_ACTION VARCHAR(255),
  ERC_MESSAGE VARCHAR(255),
  ERC_CLASSNAME VARCHAR(255),
  ERC_METHOD VARCHAR(255),
  ERC_FILE VARCHAR(255),
  ERC_LINE INT,
  ERC_STACK IMAGE,
  ERC_ROLE VARCHAR(255),
  constraint PK_EXT_ARCHIVE_ERROR PRIMARY KEY (EAE_ARC_ID)
);

insert into ORC_SEQUENCE_COUNTER( sco_category, sco_counter ) 
  values ( 'EXT.ARCHIVE', 1 );

update ORC_MONITOR_TABLESETTINGS 
   set ORC_COLUMN_PATTERN = ORC_COLUMN_PATTERN + ',y'
 where ORC_TABLECLASS = 'ProcessOverviewTable'
   and replace(ORC_COLUMN_PATTERN, 'n', 'y') = 'y,y,y,y,y,y,y';

GO
