
/* Renaming Column, Change Column Datatyp, Drop & Recreate Index of Table */
	/* 05.09.2012 Update Datatype of Column MLI_CREATED_AT (TIMESTAMP --> DATETIME) */
EXEC sp_rename 'ORC_MESSAGE_LIST.MLI_IS_SYSTEM', 'MLI_TYPE', 'COLUMN';
ALTER TABLE ORC_MESSAGE_LIST ALTER COLUMN MLI_TYPE INT;   
ALTER TABLE ORC_MESSAGE_LIST ADD MLI_CREATED_AT DATETIME;
DROP INDEX IDX_ORC_MSG_LIST_ID ON ORC_MESSAGE_LIST;
ALTER TABLE ORC_MESSAGE_LIST ALTER COLUMN  MLI_ID BIGINT;
CREATE INDEX IDX_ORC_MSG_LIST_ID ON ORC_MESSAGE_LIST(MLI_ID) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

/* Drop Index, Change COLUMN Datatyp, recreate Index of Table */
DROP INDEX	IDX_ORC_MSG_LISTENT_ID_REFER ON ORC_MESSAGE_LIST_ENTRY;
DROP INDEX	IDX_ORC_MSG_LISTENT_ID_MSGREF ON ORC_MESSAGE_LIST_ENTRY;
ALTER TABLE ORC_MESSAGE_LIST_ENTRY ALTER COLUMN MLE_ID BIGINT;
CREATE INDEX IDX_ORC_MSG_LISTENT_ID_REFER ON ORC_MESSAGE_LIST_ENTRY(MLE_ID, MLE_REFERENCE) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
CREATE INDEX IDX_ORC_MSG_LISTENT_ID_MSGREF ON ORC_MESSAGE_LIST_ENTRY(MLE_ID, MLE_REFERENCE) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
		
/* Drop Index, Change COLUMN Datatyp, recreate Index of Table */
DROP INDEX	IDX_ORC_MSG_LISTPRP_ID_REF_KEY ON ORC_MESSAGE_LIST_ENTRY_PROP;
DROP INDEX	IDX_ORC_MSG_LISTPRP_ID_KEY_VAL ON ORC_MESSAGE_LIST_ENTRY_PROP;
ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP ALTER COLUMN MLP_ID BIGINT;
CREATE INDEX IDX_ORC_MSG_LISTPRP_ID_REF_KEY ON ORC_MESSAGE_LIST_ENTRY_PROP(MLP_ID, MLP_REFERENCE, MLP_KEY) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
CREATE INDEX IDX_ORC_MSG_LISTPRP_ID_KEY_VAL ON ORC_MESSAGE_LIST_ENTRY_PROP(MLP_ID, MLP_KEY, MLP_VALUE) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);	
 
/* Drop Index, Change COLUMN Datatyp, recreate Index of Table */
DROP INDEX	IDX_ORC_MSG_LISTIN_ID_IDX ON ORC_MESSAGE_LIST_INDEX;
DROP INDEX	IDX_ORC_MSG_LISTIN_ID_REF ON ORC_MESSAGE_LIST_INDEX;
ALTER TABLE ORC_MESSAGE_LIST_INDEX ALTER COLUMN MLI_ID BIGINT;
CREATE INDEX IIDX_ORC_MSG_LISTIN_ID_IDX ON ORC_MESSAGE_LIST_INDEX(MLI_ID, MLI_INDEX) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
CREATE INDEX IDX_ORC_MSG_LISTIN_ID_REF ON ORC_MESSAGE_LIST_INDEX(MLI_ID, MLI_REFERENCE) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

/* Alter table */
DROP TABLE ORC_MESSAGE_REFERERS;

CREATE TABLE ORC_MESSAGE_REFERERS
(
  MRE_OBJECT_ID  VARCHAR(255),
  MRE_REFERRER_ID  VARCHAR(255),
  MRE_DELETE_FLAG VARCHAR(1),
  MRE_REF_TYPE INT,
  MRE_OBJECT_TYPE INT,
  MRE_MESSAGELIST_ID BIGINT
);

ALTER TABLE ORC_MESSAGE_REFERERS SET (LOCK_ESCALATION = DISABLE)
GO

CREATE INDEX IDX_MSG_REFERRER_PROCESS_ID ON ORC_MESSAGE_REFERERS(MRE_REFERRER_ID) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

CREATE INDEX IDX_MSG_REFERRER_MESSAGE_ID ON ORC_MESSAGE_REFERERS(MRE_OBJECT_ID) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

CREATE INDEX IDX_MSG_REFERRER_DELETE_FLAG ON ORC_MESSAGE_REFERERS(MRE_DELETE_FLAG) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
GO

CREATE TABLE ORC_PROCESSINSTANCE_STATE (
  		PRS_ID            VARCHAR(255) NOT NULL,
  		PRS_DATA          VARBINARY(MAX),
  		PRS_PROCESSMODELL VARCHAR(255) DEFAULT NULL);

ALTER TABLE ORC_PROCESSINSTANCE_STATE SET (LOCK_ESCALATION = DISABLE);

CREATE INDEX IDX_ORC_PROCESINST_STATE_ID ON orc_processinstance_state(PRS_ID) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
 		 
ALTER TABLE ORC_EVENT_PROCESS_TOKEN
  add EVT_ORCHESTRA_LINK VARCHAR(254);


CREATE TABLE ORC_USERSCENARIOMAP
(
  USER_ID      VARCHAR(254)               NOT NULL,
  SCENARIO_ID  VARCHAR(254)               NOT NULL
);

ALTER TABLE ORC_USERSCENARIOMAP SET (LOCK_ESCALATION = DISABLE);

ALTER TABLE ORC_USERSCENARIOMAP 
	ADD CONSTRAINT PK_ORC_USR_SCEN_MAP PRIMARY KEY(USER_ID, SCENARIO_ID)
	WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
 
INSERT INTO ORC_SEC_ROLE_V2 (OSR_SCENARIO,OSR_IDENTIFIER,OSR_DESC) 
     values ('RUNTIME','RUNTIME:Scenario.SuperUser',null);


INSERT INTO ORC_SEC_USER_ROLES_V2 
    SELECT
        OSC_UNIQUE_ID,'Scenario.SuperUser'
    FROM
        ORC_SEC_CREDENTIAL_V2
    WHERE OSC_SCENARIO = 'RUNTIME'; 
	 

ALTER TABLE ORC_PROCESS_RUNTIME_STATE 
        ADD PRS_GLOBAL_TID VARCHAR(64);
		
ALTER TABLE ORC_PROCESS_RUNTIME_STATE 
  ADD PRS_IS_STANDALONE INT DEFAULT NULL;

CREATE TABLE ORC_TRANSACTION 
(
  TRA_TAID        VARCHAR(64)	NOT NULL,
  TRA_CREATE_DATE timestamp		NOT NULL,
  TRA_STATE       int			NOT NULL
);

ALTER TABLE ORC_TRANSACTION SET (LOCK_ESCALATION = DISABLE);

ALTER TABLE ORC_TRANSACTION ADD CONSTRAINT PK_ORC_TRANSACTION PRIMARY KEY (TRA_TAID)
 WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);


CREATE TABLE ORC_TRANSACTION_LOG_ENTRY 
(
  TLE_TAID    VARCHAR(64) DEFAULT NULL,
  TLE_ACTION  VARCHAR(64) DEFAULT NULL,
  TLE_INFO    VARCHAR(64) DEFAULT NULL,
  TLE_MODE    int		  DEFAULT NULL,
  TLE_ORDER   bigint      DEFAULT NULL
 );

ALTER TABLE ORC_TRANSACTION_LOG_ENTRY SET (LOCK_ESCALATION = DISABLE);
  
CREATE INDEX IDX_ORC_TRANSACTION_LOG_ENTRY ON ORC_TRANSACTION_LOG_ENTRY (TLE_TAID) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
  
CREATE TABLE ORC_TRANSACTION_BRANCH 
(
  TBR_TAID 	   VARCHAR(64) DEFAULT NULL,
  TBR_TYP      VARCHAR(64) DEFAULT NULL,
  TBR_BRANCH   VARCHAR(64) DEFAULT NULL,
  TBR_DATA     VARBINARY(MAX)
 );  

ALTER TABLE ORC_TRANSACTION_BRANCH SET (LOCK_ESCALATION = DISABLE);
  
CREATE INDEX IDX_ORC_TRANSACTION_BRANCH on ORC_TRANSACTION_BRANCH (TBR_TAID) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

CREATE TABLE ORC_ESB_SIGNAL_STATE
(
    EST_IDENTIFIER VARCHAR(64) NULL,
    EST_DATE datetime NOT NULL,
    EST_NODE VARCHAR(64) NULL
);

ALTER TABLE ORC_ESB_SIGNAL_STATE SET (LOCK_ESCALATION = DISABLE);

/* 05.09.2012 Update Column-Name JCL_DEPLAYED_AT to JCL_DEPLOYED_AT + Update Datatyp (TIMESTAMP --> DATETIME) */	
CREATE TABLE ORC_JAVA_CLASS 
(
	JCL_SCENARIO	VARCHAR(250),
	JCL_NAME		VARCHAR(250),
	JCL_DATA		VARBINARY(MAX),
	JCL_DEPLOYED_AT	DATETIME,
	JCL_UNIQUE_NAME	VARCHAR(250) NOT NULL
);

ALTER TABLE ORC_JAVA_CLASS SET (LOCK_ESCALATION = DISABLE);
	
CREATE UNIQUE INDEX UIDX_ORC_JAVA_CLASS 
	ON ORC_JAVA_CLASS (JCL_SCENARIO, JCL_NAME) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);
	
ALTER TABLE ORC_JAVA_CLASS ADD CONSTRAINT PK_ORC_JAVA_CLASS PRIMARY KEY (JCL_UNIQUE_NAME)
 WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

GO
