/* MS SQL Skript */

/* 5.09.2012 */

/* Create Index */

CREATE INDEX IDX_MSG_REFERRER_MESSAGELIST_ID ON ORC_MESSAGE_REFERERS(MRE_MESSAGELIST_ID) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

CREATE INDEX IDX_ORC_MSG_LIST_CREATED_AT ON ORC_MESSAGE_LIST(MLI_CREATED_AT) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF);

GO
