
DROP INDEX IDX_ORC_EVT_PROCESS_VAR_VALUE ON ORC_EVT_PROCESS_VARIABLES
GO

CREATE INDEX IDX_ORC_EVT_PROCESS_VAR_VALUE ON ORC_EVT_PROCESS_VARIABLES (EVV_VALUE, EVV_IS_MESSAGE) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS = OFF)
GO

