-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.5.1.0.xml
-- Ran at: 31.07.14 16:22
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-01::akn::(Checksum: 6:b4b1438959cdfa538f2ecc0d852116c8)
ALTER TABLE [ORC_PROCESS_FIFO_SCHEDULE] ALTER COLUMN [PFS_ID] VARCHAR(50)
GO

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-02::akn::(Checksum: 6:6f0693225b07d78edc17111d23bfa338)
ALTER TABLE [ORC_ALERT_DATA] ADD [NODE_ID] VARCHAR(255) NOT NULL CONSTRAINT DF_ORC_ALERT_DATA_NODE_ID DEFAULT 'ORC'
GO

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-03::akn::(Checksum: 6:4513c43b495676b0bd6cefcafef2f27d)
DROP INDEX [ORC_SEQUENCE_COUNTER].IDX_SEQ_COUNTER_CATEGORY
GO

UPDATE [ORC_SEQUENCE_COUNTER] SET [SCO_CATEGORY] = 'ORC' WHERE [SCO_CATEGORY] IS NULL
GO

ALTER TABLE [ORC_SEQUENCE_COUNTER] ALTER COLUMN [SCO_CATEGORY] VARCHAR(32) NOT NULL
GO

ALTER TABLE [ORC_SEQUENCE_COUNTER] ADD CONSTRAINT [PK_SEQ_COUNTER_CATEGORY] PRIMARY KEY ([SCO_CATEGORY]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

DROP INDEX [ORC_MESSAGE_DATA].IDX_MSG_DATA_MSG_ID
GO

UPDATE [ORC_MESSAGE_DATA] SET [MSD_MSG_ID] = 'ORC' WHERE [MSD_MSG_ID] IS NULL
GO

ALTER TABLE [ORC_MESSAGE_DATA] ALTER COLUMN [MSD_MSG_ID] VARCHAR(100) NOT NULL
GO

ALTER TABLE [ORC_MESSAGE_DATA] ADD CONSTRAINT [PK_MSG_DATA_MSG_ID] PRIMARY KEY ([MSD_MSG_ID]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.5.1.0-04::akn::(Checksum: 6:706e1b31fb477bed8328e25a8d68791d)
CREATE TABLE [ORC_COMMIT_DESC] ([OCD_TAID] VARCHAR(255) NOT NULL, [OCD_TIME] datetime, [OCD_NODE] VARCHAR(255) NOT NULL)
GO

ALTER TABLE [ORC_COMMIT_DESC] SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE [ORC_COMMIT_DESC] ADD CONSTRAINT [PK_COMDE_TAID_NODE] PRIMARY KEY ([OCD_TAID], [OCD_NODE]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

ALTER TABLE [ORC_WORK_QUEUE] ADD [NEXT_SCHEDULE_TIME] datetime
GO

CREATE INDEX IDX_WORK_QUEUE_S_T_Q_N ON [ORC_WORK_QUEUE]([STATE], [TARGET_NODE], [QUEUE_TYPE], [NEXT_SCHEDULE_TIME]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

ALTER TABLE [ORC_TOPIC_QUEUE] ADD [NEXT_SCHEDULE_TIME] datetime
GO

CREATE INDEX IDX_TOPIC_QUEUE_S_T_Q_N ON [ORC_TOPIC_QUEUE]([STATE], [TARGET_NODE], [QUEUE_TYPE], [NEXT_SCHEDULE_TIME]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

-- Changeset /opt/liquibase/data/orchestra_4.5.1.0.xml::change-4.4.3.2-02::akn::(Checksum: 6:2a766a9e610e3f13dfb7cdeb2ac61cab)
ALTER TABLE [ORC_KPI_INSTANCE] ADD CONSTRAINT [PK_ORC_KPI_INSTANCE] PRIMARY KEY ([KIN_IDENTIFIER]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

ALTER TABLE [ORC_KPI_DIM_VALUE] ADD CONSTRAINT [PK_ORC_KPI_DIM_VALUE] PRIMARY KEY ([KDV_INSTANCEID], [KDV_NAME]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

ALTER TABLE [ORC_KPI_VALUE] ADD CONSTRAINT [PK_ORC_KPI_VALUE] PRIMARY KEY ([KVA_INSTANCEID], [KVA_TIMEINDEX]) WITH (ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = OFF)
GO

