CREATE TABLE ORC_JBPM_PROCESS_DEFINITION
(
  PMO_SCENARIO     VARCHAR(250),
  PMO_NAME         VARCHAR(250),
  PMO_DATA         blob,
  PMO_DEPLOYED_AT  DATE,
  PMO_UNIQUE_NAME  VARCHAR(250)
)ENGINE= innodb;


commit;
