ALTER TABLE orc_process_fifo_schedule
 ADD PFS_LOGICAL_ORDER BIGINT AFTER PFS_OWNER_NODE;
 
 ALTER TABLE orc_process_fifo_schedule
  ADD UNIQUE INDEX IDX_PROCESS_FIFO_KEY_AUTO (PFS_LOGICAL_ORDER);

 ALTER TABLE orc_process_fifo_schedule
 CHANGE PFS_LOGICAL_ORDER PFS_LOGICAL_ORDER BIGINT(20) AUTO_INCREMENT;

ALTER TABLE orc_process_fifo_schedule DROP INDEX IDX_PROCESS_FIFO_SCHED_REF_ID;
ALTER TABLE orc_process_fifo_schedule
  ADD INDEX IDX_PROCESS_FIFO_SCHED_REF_ID (PFS_MODELL_REFERENCE, PFS_ID, PFS_STATE, PFS_LOGICAL_ORDER);

  
 create table ORC_TOPIC_QUEUE_CPY as select * from ORC_TOPIC_QUEUE;
 
 TRUNCATE TABLE ORC_TOPIC_QUEUE;
 
ALTER TABLE orc_topic_queue
 ADD LOGICAL_ORDER BIGINT AFTER DELETETOKEN; 
 
ALTER TABLE orc_topic_queue
  ADD UNIQUE INDEX IDX_TOPIC_QUEUE_LOG_ORDER (LOGICAL_ORDER);

ALTER TABLE orc_topic_queue
 CHANGE LOGICAL_ORDER LOGICAL_ORDER BIGINT(20) AUTO_INCREMENT;  
 
 INSERT INTO ORC_TOPIC_QUEUE(ITEMTYPE,DISCRIMINATOR,CREATEDAT,WORKOBJECT,ID,ACTION,NAME,STATE,TARGET_NODE,NODE_TICK,QUEUE_TYPE,PRIORITY,ORC_TOPIC_OWNER,ORC_TOPIC_ID,NEXT_SCHEDULE_TIME,DELETETOKEN) 
SELECT ITEMTYPE,DISCRIMINATOR,CREATEDAT,WORKOBJECT,ID,ACTION,NAME,STATE,TARGET_NODE,NODE_TICK,QUEUE_TYPE,PRIORITY,ORC_TOPIC_OWNER,ORC_TOPIC_ID,NEXT_SCHEDULE_TIME,DELETETOKEN 
  FROM ORC_TOPIC_QUEUE_CPY ORDER BY ID;

  ALTER TABLE orc_topic_queue DROP INDEX IDX_TOPIC_QUEUE_STAT_TYP_PRIO;
ALTER TABLE orc_topic_queue
  ADD INDEX IDX_TOPIC_QUEUE_STAT_TYP_PRIO (STATE, QUEUE_TYPE, PRIORITY, ID, LOGICAL_ORDER);

  ALTER TABLE orc_topic_queue DROP INDEX IDX_TOPIC_QUEUE_STATE_TYPE_ID;
ALTER TABLE orc_topic_queue
  ADD INDEX IDX_TOPIC_QUEUE_STATE_TYPE_ID (STATE, QUEUE_TYPE, ID, LOGICAL_ORDER);

DROP TABLE ORC_TOPIC_QUEUE_CPY;

ALTER TABLE ORC_ESB_TCP_CELL ADD ETC_ENV_CONF tinyint(1) NULL;
ALTER TABLE ORC_ESB_TCP_CELL ADD ETC_NODE_NAME varchar(50) NULL;
ALTER TABLE ORC_ESB_ROUTER ADD ERO_ENV_CONF tinyint(1) NULL ;

ALTER TABLE ORC_PROCESS_RUNTIME_STATE ADD PRS_LOGICAL_ORDER BIGINT;
 
ALTER TABLE ORC_PROCESS_RUNTIME_STATE ADD UNIQUE INDEX IDX_PROCESS_RT_STATE_KEY_AUTO (PRS_LOGICAL_ORDER);

ALTER TABLE ORC_PROCESS_RUNTIME_STATE CHANGE PRS_LOGICAL_ORDER PRS_LOGICAL_ORDER BIGINT(20) AUTO_INCREMENT;

ALTER TABLE ORC_PROCESS_RUNTIME_STATE ADD PRS_REVISION BIGINT(20) NULL;

ALTER TABLE ORC_PROCESS_FIFO_SCHED_CACHE ADD PFC_STATE varchar(10);
