-- *********************************************************************
-- Create Database Script
-- *********************************************************************
-- Change Log: /opt/liquibase/data/orchestra_4.5.3.0.xml
-- Ran at: 08.12.14 17:04
-- Liquibase version: 2.0.5
-- *********************************************************************

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-01::akn::(Checksum: 6:0090e88c99824bbaff951b4d7602fa81)
UPDATE ORC_CLUSTER_ENVIRONMENT SET CEN_NODE_NAME = 'ORC' WHERE CEN_NODE_NAME IS NULL;

ALTER TABLE ORC_CLUSTER_ENVIRONMENT ALTER COLUMN  CEN_NODE_NAME SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_CLUSTER_ENVIRONMENT');

ALTER TABLE ORC_CLUSTER_ENVIRONMENT ADD CONSTRAINT PK_CLUSTER_ENV PRIMARY KEY (CEN_NODE_NAME);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_CLUSTER_ENVIRONMENT');

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-02::akn::(Checksum: 6:12ea4392b233c2bd31f0c4e6a124bf9c)
ALTER TABLE ORC_SEQUENCE_COUNTER DROP PRIMARY KEY;

ALTER TABLE ORC_SEQUENCE_COUNTER ALTER COLUMN SCO_CATEGORY SET DATA TYPE VARCHAR(64);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEQUENCE_COUNTER');

UPDATE ORC_SEQUENCE_COUNTER SET SCO_CATEGORY = 'ORC' WHERE SCO_CATEGORY IS NULL;

ALTER TABLE ORC_SEQUENCE_COUNTER ALTER COLUMN  SCO_CATEGORY SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEQUENCE_COUNTER');

ALTER TABLE ORC_SEQUENCE_COUNTER ADD CONSTRAINT PK_SEQ_COUNTER_CAT PRIMARY KEY (SCO_CATEGORY);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_SEQUENCE_COUNTER');

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-03::akn::(Checksum: 6:ab39234df3ed46e61f94f447df73cda7)
DROP INDEX IDX_ORC_WORK_QUEUE_2;

DROP INDEX IDX_PROCESS_FIFO_SCHEDULE_ID;

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-05::akn::(Checksum: 6:c882e87463c0e72fd74bd0609ef2af1b)
INSERT INTO ORC_CLUSTER_LOCK (ORC_LOCK_NAME, ORC_LOCK_SCENARIO) VALUES ('LTA', 'GLOBAL');

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-06::akn::(Checksum: 6:fe9ef52154db13164a7a9124e8499a83)
ALTER TABLE ORC_PROCESSINSTANCE_STATE ADD PRS_CLUSTER_LEASE VARCHAR(255);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESSINSTANCE_STATE');

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-08-1::akn::(Checksum: 6:1de928410dd90a4f75b45156a2de6601)
ALTER TABLE ORC_PROCESS_FIFO_SCHED_CACHE DROP PRIMARY KEY;

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-08-2::akn::(Checksum: 6:f4b13793aec7aefd374ab5c27832d4f5)
ALTER TABLE ORC_PROCESS_FIFO_SCHED_CACHE ADD CONSTRAINT PK_PROC_FIFO_CACHE PRIMARY KEY (PFC_ID, PFC_MODELL_REFERENCE);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_PROCESS_FIFO_SCHED_CACHE');

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-09::akn::(Checksum: 6:d5a4eca404b21fbbb510ff78fbf1e77b)
DROP INDEX IDX_PROCESS_FIFO_CACHE;

CREATE INDEX IDX_PROCESS_FIFO_CACHE ON ORC_PROCESS_FIFO_SCHED_CACHE(PFC_MODELL_REFERENCE, PFC_TARGET_NODE);

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-10::akn::(Checksum: 6:2c09d4c12f15a3008d85d5f8a136ee4c)
DROP INDEX IDX_ORC_MSG_LIST_ID;

UPDATE ORC_MESSAGE_LIST SET MLI_ID = 0 WHERE MLI_ID IS NULL;

ALTER TABLE ORC_MESSAGE_LIST ALTER COLUMN  MLI_ID SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST');

ALTER TABLE ORC_MESSAGE_LIST ADD CONSTRAINT PK_ORC_MSG_LIST_ID PRIMARY KEY (MLI_ID);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST');

DROP INDEX IDX_ORC_MSG_LISTENT_ID_MSGREF;

DROP INDEX IDX_ORC_MSG_LISTENT_ID_REFER;

UPDATE ORC_MESSAGE_LIST_ENTRY SET MLE_ID = 0 WHERE MLE_ID IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY ALTER COLUMN  MLE_ID SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST_ENTRY');

UPDATE ORC_MESSAGE_LIST_ENTRY SET MLE_REFERENCE = 'dummy' WHERE MLE_REFERENCE IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY ALTER COLUMN  MLE_REFERENCE SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST_ENTRY');

ALTER TABLE ORC_MESSAGE_LIST_ENTRY ADD CONSTRAINT PK_MLE_ID_REFER PRIMARY KEY (MLE_ID, MLE_REFERENCE);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST_ENTRY');

DROP INDEX IDX_ORC_MSG_LISTPRP_ID_KEY_VAL;

DROP INDEX IDX_ORC_MSG_LISTPRP_ID_REF_KEY;

UPDATE ORC_MESSAGE_LIST_ENTRY_PROP SET MLP_ID = 0 WHERE MLP_ID IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP ALTER COLUMN  MLP_ID SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST_ENTRY_PROP');

UPDATE ORC_MESSAGE_LIST_ENTRY_PROP SET MLP_KEY = 'dummy' WHERE MLP_KEY IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP ALTER COLUMN  MLP_KEY SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST_ENTRY_PROP');

UPDATE ORC_MESSAGE_LIST_ENTRY_PROP SET MLP_REFERENCE = 'dummy' WHERE MLP_REFERENCE IS NULL;

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP ALTER COLUMN  MLP_REFERENCE SET NOT NULL;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST_ENTRY_PROP');

ALTER TABLE ORC_MESSAGE_LIST_ENTRY_PROP ADD CONSTRAINT PK_MLP_ID_KEY_REF PRIMARY KEY (MLP_ID, MLP_KEY, MLP_REFERENCE);

CALL SYSPROC.ADMIN_CMD ('REORG TABLE ORC_MESSAGE_LIST_ENTRY_PROP');

CREATE INDEX IDX_ORC_MSG_LISTPRP_ID_KEY_VAL ON ORC_MESSAGE_LIST_ENTRY_PROP(MLP_ID, MLP_KEY, MLP_VALUE);

-- Changeset /opt/liquibase/data/orchestra_4.5.3.0.xml::change-4.5.3.0-11::akn::(Checksum: 6:ee5857d2d2fe76046d476652158f59c4)
DROP INDEX IDX_PROC_FIFO_SCHED_MODEL_REF;

