CREATE TABLE ORC_DBS_PAGE
(
  DPA_MESSAGE_ID  VARCHAR(255),
  DPA_ID          integer                    NOT NULL,
  DEL_DATA        BLOB,
  DPA_PAGE_TYPE   integer
)ENGINE= innodb;


CREATE INDEX IDX_DBS_PAGE ON ORC_DBS_PAGE (DPA_MESSAGE_ID, DPA_ID);


CREATE TABLE ORC_SEC_USER_CERTIFICATE
(
  OUP_SCENARIO     VARCHAR(255)           NOT NULL,
  OUP_USER_ID      VARCHAR(255)           NOT NULL,
  OUP_CERTIFICATE  BLOB
)ENGINE= innodb;


CREATE INDEX IDX_ORC_SEC_USER_CERTIFICATE ON ORC_SEC_USER_CERTIFICATE (OUP_SCENARIO, OUP_USER_ID);

CREATE TABLE ORC_BUSINESS_TRANSACTION
(
  OBT_SCENARIO       VARCHAR(254),
  OBT_OWNER          VARCHAR(254),
  OBT_TA_IDENTIFIER  VARCHAR(254),
  OBT_CREATED        TIMESTAMP NULL,
  OBT_TYPE           VARCHAR(1)
)ENGINE= innodb;


CREATE INDEX IDX_ORC_BUSINESS_TRANSACTION ON ORC_BUSINESS_TRANSACTION (OBT_SCENARIO, OBT_OWNER, OBT_TA_IDENTIFIER);

ALTER TABLE ORC_MESSAGE_PROPERTIES MODIFY MPR_VALUE VARCHAR(1023);

commit;

