
CREATE INDEX IDX_PROCESS_FIFO_SCHEDULE_MODEL_REF ON ORC_PROCESS_FIFO_SCHEDULE( PFS_MODELL_REFERENCE );

ALTER TABLE ORC_WORK_QUEUE MODIFY WORKOBJECT LONGBLOB;

ALTER TABLE ORC_TOPIC_QUEUE MODIFY WORKOBJECT LONGBLOB;

commit;
